/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/rooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 채팅방 생성
         * @description 새로운 채팅방을 생성합니다.
         *
         *     ## 요청 예시
         *     ```json
         *     {
         *       "user_id": "user-123",
         *       "storybook_url": "https://storybook.example.com"
         *     }
         *     ```
         *
         *     ## 필드 설명
         *     - `user_id` (필수): 사용자 ID
         *     - `storybook_url` (선택): Storybook URL (참고용)
         *
         *     ## 응답
         *     - `id`: 생성된 채팅방 UUID
         *     - `storybook_url`: Storybook URL
         *     - `schema_key`: 스키마 경로 (초기값: null, POST /components/upload로 설정 가능)
         *     - `user_id`: 사용자 ID
         *     - `created_at`: 생성 시간 (ms timestamp)
         *
         *     ## 스키마 설정 방법
         *     채팅방 생성 후 `POST /components/upload`로 스키마를 업로드하면 자동으로 `schema_key`가 설정됩니다.
         */
        post: operations["create_room_rooms_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rooms/{room_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 채팅방 조회
         * @description 채팅방 ID로 채팅방 정보를 조회합니다.
         */
        get: operations["get_room_rooms__room_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 채팅방 업데이트
         * @description 채팅방 정보를 업데이트합니다.
         *
         *     ## 요청 예시
         *     ```json
         *     {
         *       "storybook_url": "https://new-storybook.example.com",
         *       "schema_key": "schemas/new-design-system.json"
         *     }
         *     ```
         *
         *     ## 업데이트 가능한 필드
         *     - `storybook_url`: Storybook URL
         *     - `schema_key`: Firebase Storage 스키마 경로
         */
        patch: operations["update_room_rooms__room_id__patch"];
        trace?: never;
    };
    "/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * AI 채팅 (Non-streaming)
         * @description 자연어로 UI를 설명하면 React TSX 코드를 생성합니다.
         *
         *     ## 요청 예시
         *     ```json
         *     {
         *       "message": "로그인 페이지 만들어줘",
         *       "room_id": "550e8400-e29b-41d4-a716-446655440000"
         *     }
         *     ```
         *
         *     ## 응답 구조
         *     - `message`: AI 원본 응답
         *     - `parsed.conversation`: 한국어 설명
         *     - `parsed.files`: 생성된 코드 파일 목록
         *     - `usage`: 토큰 사용량
         *
         *     ## room_id
         *     채팅방 ID (필수). 메시지가 해당 채팅방에 저장됩니다.
         *
         *     ## 스키마 모드
         *     채팅방의 schema_key가 설정되어 있으면 Firebase Storage에서 컴포넌트 스키마를 로드합니다.
         *     없으면 자유 모드(React + Tailwind CSS)로 동작합니다.
         */
        post: operations["chat_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * AI 채팅 (Streaming)
         * @description SSE(Server-Sent Events)를 통해 실시간 스트리밍 응답을 받습니다.
         *
         *     ## 요청 예시
         *     ```json
         *     {
         *       "message": "로그인 페이지 만들어줘",
         *       "room_id": "550e8400-e29b-41d4-a716-446655440000"
         *     }
         *     ```
         *
         *     ## 이벤트 타입
         *
         *     | 타입 | 설명 | 필드 |
         *     |------|------|------|
         *     | `chat` | 대화 텍스트 (실시간) | `text` |
         *     | `code` | 코드 파일 (완성 후) | `path`, `content` |
         *     | `done` | 스트리밍 완료 | - |
         *     | `error` | 오류 발생 | `error` |
         *
         *     ## SSE 응답 예시
         *     ```
         *     data: {"type": "chat", "text": "모던한 "}
         *
         *     data: {"type": "chat", "text": "로그인 페이지입니다."}
         *
         *     data: {"type": "code", "path": "src/pages/Login.tsx", "content": "import..."}
         *
         *     data: {"type": "done"}
         *     ```
         *
         *     ## room_id
         *     채팅방 ID (필수). 스트리밍 완료 후 메시지가 해당 채팅방에 저장됩니다.
         */
        post: operations["chat_stream_chat_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/components": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 컴포넌트 스키마 조회
         * @description 현재 로드된 디자인 시스템 컴포넌트 스키마를 반환합니다.
         */
        get: operations["get_components_components_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/components/reload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 컴포넌트 스키마 리로드
         * @description component-schema.json 파일을 다시 로드하여 시스템 프롬프트를 갱신합니다.
         */
        post: operations["reload_components_components_reload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/components/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 스키마 업로드
         * @description 클라이언트가 추출한 컴포넌트 스키마를 Firebase Storage에 업로드합니다.
         *
         *     ## 사용 흐름
         *     1. `POST /rooms`로 채팅방 생성 → room_id 획득
         *     2. 클라이언트에서 react-docgen-typescript로 스키마 추출
         *     3. 이 API로 스키마 업로드 (room_id 필수)
         *
         *     ## 저장 경로
         *     `exports/{room_id}/component-schema.json`
         */
        post: operations["upload_schema_components_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/components/storage/{schema_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Storage 스키마 조회
         * @description Firebase Storage에서 스키마를 조회합니다.
         */
        get: operations["get_storage_schema_components_storage__schema_key__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 서버 상태 확인
         * @description 서버가 정상적으로 실행 중인지 확인합니다.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ChatRequest
         * @description 채팅 요청
         * @example {
         *       "message": "로그인 페이지 만들어줘",
         *       "room_id": "550e8400-e29b-41d4-a716-446655440000"
         *     }
         * @example {
         *       "message": "대시보드 만들어줘",
         *       "room_id": "550e8400-e29b-41d4-a716-446655440000"
         *     }
         */
        ChatRequest: {
            /**
             * Message
             * @description 사용자 메시지 (최대 10,000자)
             * @example 로그인 페이지 만들어줘
             */
            message: string;
            /**
             * Room Id
             * @description 채팅방 ID
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            room_id: string;
            /**
             * Stream
             * @description 스트리밍 응답 여부 (True면 /stream 엔드포인트 사용 권장)
             * @default false
             */
            stream: boolean;
        };
        /**
         * ChatResponse
         * @description 채팅 응답 (Non-streaming)
         * @example {
         *       "message": {
         *         "content": "모던한 로그인 페이지입니다.\n\n<file path=\"src/pages/Login.tsx\">import { Button } from '@/components';\n\nconst Login = () => <Button>로그인</Button>;\n\nexport default Login;</file>",
         *         "role": "assistant"
         *       },
         *       "parsed": {
         *         "conversation": "모던한 로그인 페이지입니다.",
         *         "files": [
         *           {
         *             "content": "import { Button } from '@/components';\n\nconst Login = () => <Button>로그인</Button>;\n\nexport default Login;",
         *             "path": "src/pages/Login.tsx"
         *           }
         *         ],
         *         "raw": "..."
         *       },
         *       "usage": {
         *         "completion_tokens": 800,
         *         "prompt_tokens": 1500,
         *         "total_tokens": 2300
         *       }
         *     }
         */
        ChatResponse: {
            /** @description AI 응답 메시지 */
            message: components["schemas"]["Message"];
            /** @description 파싱된 응답 (conversation과 files 분리) */
            parsed?: components["schemas"]["ParsedResponse"] | null;
            /**
             * Usage
             * @description 토큰 사용량 정보
             * @example {
             *       "completion_tokens": 800,
             *       "prompt_tokens": 1500,
             *       "total_tokens": 2300
             *     }
             */
            usage?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * CreateRoomRequest
         * @description 채팅방 생성 요청
         * @example {
         *       "storybook_url": "https://storybook.example.com",
         *       "user_id": "user-123"
         *     }
         */
        CreateRoomRequest: {
            /**
             * User Id
             * @description 사용자 ID
             * @example user-123
             */
            user_id: string;
            /**
             * Storybook Url
             * @description Storybook URL (참고용)
             * @example https://storybook.example.com
             */
            storybook_url?: string | null;
        };
        /**
         * FileContent
         * @description 생성된 파일 정보
         * @example {
         *       "content": "import { Button, Field } from '@/components';\n\nconst Login = () => {\n  return (\n    <div>\n      <Field label=\"이메일\" />\n      <Button>로그인</Button>\n    </div>\n  );\n};\n\nexport default Login;",
         *       "path": "src/pages/Login.tsx"
         *     }
         */
        FileContent: {
            /**
             * Path
             * @description 파일 경로 (예: src/pages/Login.tsx)
             * @example src/pages/Login.tsx
             */
            path: string;
            /**
             * Content
             * @description 파일 내용 (React TSX 코드)
             * @example import { Button } from '@/components';
             *
             *     const Login = () => {
             *       return <Button>로그인</Button>;
             *     };
             *
             *     export default Login;
             */
            content: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Message
         * @description 채팅 메시지
         * @example {
         *       "content": "로그인 페이지 만들어줘",
         *       "role": "user"
         *     }
         * @example {
         *       "content": "모던한 로그인 페이지입니다.\n\n<file path=\"src/pages/Login.tsx\">...</file>",
         *       "role": "assistant"
         *     }
         */
        Message: {
            /**
             * Role
             * @description 메시지 역할
             * @example user
             * @enum {string}
             */
            role: "user" | "assistant" | "system";
            /**
             * Content
             * @description 메시지 내용
             * @example 로그인 페이지 만들어줘
             */
            content: string;
        };
        /**
         * ParsedResponse
         * @description 파싱된 AI 응답 - 대화와 코드 파일 분리
         * @example {
         *       "conversation": "모던한 로그인 페이지입니다.",
         *       "files": [
         *         {
         *           "content": "import { Button } from '@/components';\n...",
         *           "path": "src/pages/Login.tsx"
         *         }
         *       ],
         *       "raw": "모던한 로그인 페이지입니다.\n\n<file path=\"src/pages/Login.tsx\">...</file>"
         *     }
         */
        ParsedResponse: {
            /**
             * Conversation
             * @description AI의 한국어 설명 (코드 외 텍스트)
             * @example 모던하고 깔끔한 로그인 페이지입니다. 그라데이션 배경과 카드 레이아웃을 사용했습니다.
             */
            conversation: string;
            /**
             * Files
             * @description 생성된 코드 파일 목록
             */
            files?: components["schemas"]["FileContent"][];
            /**
             * Raw
             * @description AI 원본 응답 (파싱 전)
             */
            raw: string;
        };
        /**
         * ReloadResponse
         * @description 스키마 리로드 응답
         */
        ReloadResponse: {
            /**
             * Message
             * @description 결과 메시지
             * @example Schema reloaded successfully
             */
            message: string;
            /**
             * Componentcount
             * @description 리로드된 컴포넌트 수
             * @example 25
             */
            componentCount: number;
        };
        /**
         * RoomResponse
         * @description 채팅방 응답
         */
        RoomResponse: {
            /**
             * Id
             * @description 채팅방 ID (UUID)
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            id: string;
            /**
             * Storybook Url
             * @description Storybook URL (참고용)
             * @example https://storybook.example.com
             */
            storybook_url?: string | null;
            /**
             * Schema Key
             * @description Firebase Storage 스키마 경로. None이면 자유 모드.
             * @example schemas/aplus-ui.json
             */
            schema_key?: string | null;
            /**
             * User Id
             * @description 사용자 ID
             * @example user-123
             */
            user_id: string;
            /**
             * Created At
             * @description 생성 시간 (ms timestamp)
             * @example 1736654400000
             */
            created_at: number;
        };
        /**
         * SchemaResponse
         * @description 스키마 조회 응답
         */
        SchemaResponse: {
            /** Schema Key */
            schema_key: string;
            /** Data */
            data: {
                [key: string]: unknown;
            };
        };
        /**
         * UpdateRoomRequest
         * @description 채팅방 업데이트 요청
         * @example {
         *       "schema_key": "schemas/aplus-ui.json",
         *       "storybook_url": "https://new-storybook.example.com"
         *     }
         */
        UpdateRoomRequest: {
            /**
             * Storybook Url
             * @description Storybook URL (참고용)
             * @example https://storybook.example.com
             */
            storybook_url?: string | null;
            /**
             * Schema Key
             * @description Firebase Storage 스키마 경로 변경
             * @example schemas/aplus-ui.json
             */
            schema_key?: string | null;
        };
        /**
         * UploadSchemaRequest
         * @description 스키마 업로드 요청
         */
        UploadSchemaRequest: {
            /**
             * Room Id
             * @description 채팅방 ID
             */
            room_id: string;
            /**
             * Data
             * @description 컴포넌트 스키마 JSON
             */
            data: {
                [key: string]: unknown;
            };
        };
        /**
         * UploadSchemaResponse
         * @description 스키마 업로드 응답
         */
        UploadSchemaResponse: {
            /**
             * Schema Key
             * @description Firebase Storage 경로
             */
            schema_key: string;
            /**
             * Component Count
             * @description 업로드된 컴포넌트 수
             */
            component_count: number;
            /**
             * Uploaded At
             * @description 업로드 시각 (ISO 8601)
             */
            uploaded_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_room_rooms_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRoomRequest"];
            };
        };
        responses: {
            /** @description 채팅방 생성 성공 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_room_rooms__room_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                room_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomResponse"];
                };
            };
            /** @description 채팅방을 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_room_rooms__room_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                room_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRoomRequest"];
            };
        };
        responses: {
            /** @description 업데이트 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomResponse"];
                };
            };
            /** @description 채팅방을 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    chat_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description 잘못된 요청 (stream=true인 경우) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 채팅방을 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description AI API 호출 실패 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    chat_stream_chat_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description SSE 스트림 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    /**
                     * @example data: {"type": "chat", "text": "모던한 로그인"}
                     *
                     *     data: {"type": "done"}
                     */
                    "text/event-stream": unknown;
                };
            };
            /** @description 채팅방을 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description AI API 호출 실패 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_components_components_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 스키마 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "version": "1.0.0",
                     *       "generatedAt": "2026-01-09T10:00:00.000Z",
                     *       "components": {
                     *         "Button": {
                     *           "displayName": "Button",
                     *           "category": "UI",
                     *           "props": {
                     *             "variant": {
                     *               "type": [
                     *                 "primary",
                     *                 "secondary"
                     *               ],
                     *               "required": false
                     *             }
                     *           }
                     *         }
                     *       }
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description 스키마 파일을 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    reload_components_components_reload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 리로드 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReloadResponse"];
                };
            };
            /** @description 스키마 파일 로드 실패 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    upload_schema_components_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadSchemaRequest"];
            };
        };
        responses: {
            /** @description 업로드 성공 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadSchemaResponse"];
                };
            };
            /** @description 잘못된 요청 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_storage_schema_components_storage__schema_key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                schema_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchemaResponse"];
                };
            };
            /** @description 스키마를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 서버 정상 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "healthy"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
}
