/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/rooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 채팅방 생성
         * @description 새로운 채팅방을 생성합니다.
         *
         *     ## 요청 예시
         *     ```json
         *     {
         *       "user_id": "user-123",
         *       "storybook_url": "https://storybook.example.com"
         *     }
         *     ```
         *
         *     ## 필드 설명
         *     - `user_id` (필수): 사용자 ID
         *     - `storybook_url` (선택): Storybook URL (참고용)
         *
         *     ## 응답
         *     - `id`: 생성된 채팅방 UUID
         *     - `storybook_url`: Storybook URL
         *     - `schema_key`: 스키마 경로 (POST /rooms/{room_id}/schemas로 설정)
         *     - `user_id`: 사용자 ID
         *     - `created_at`: 생성 시간 (ms timestamp)
         *
         *     ## 스키마 설정 방법
         *     채팅방 생성 후 `POST /rooms/{room_id}/schemas`로 스키마를 생성하면 자동으로 `schema_key`가 설정됩니다.
         */
        post: operations["createRoom"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rooms/{room_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 채팅방 조회
         * @description 채팅방 ID로 채팅방 정보를 조회합니다.
         */
        get: operations["getRoom"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 채팅방 업데이트
         * @description 채팅방 정보를 업데이트합니다.
         *
         *     ## 요청 예시
         *     ```json
         *     {
         *       "storybook_url": "https://new-storybook.example.com",
         *       "schema_key": "schemas/new-design-system.json"
         *     }
         *     ```
         *
         *     ## 업데이트 가능한 필드
         *     - `storybook_url`: Storybook URL
         *     - `schema_key`: Firebase Storage 스키마 경로
         */
        patch: operations["updateRoom"];
        trace?: never;
    };
    "/rooms/{room_id}/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 채팅 이미지 업로드
         * @description Firebase Storage에 이미지를 업로드하고 URL을 반환합니다.
         *
         *     ## 사용 흐름
         *     1. 이 API로 이미지 업로드 → URL 획득
         *     2. `/chat/stream`에 `image_urls` 파라미터로 전달
         *
         *     ## 저장 경로
         *     `user_uploads/{room_id}/{timestamp}_{uuid}.{ext}`
         *
         *     ## 지원 형식
         *     - image/jpeg, image/png, image/gif, image/webp
         *     - 최대 크기는 서버 설정에 따름
         */
        post: operations["uploadRoomImage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rooms/{room_id}/schemas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 채팅방 스키마 조회
         * @description 채팅방에 연결된 컴포넌트 스키마를 조회합니다.
         */
        get: operations["getRoomSchema"];
        put?: never;
        /**
         * 컴포넌트 스키마 생성
         * @description 클라이언트가 추출한 컴포넌트 스키마를 Firebase Storage에 업로드합니다.
         *
         *     ## 사용 흐름
         *     1. `POST /rooms`로 채팅방 생성 → room_id 획득
         *     2. 클라이언트에서 react-docgen-typescript로 스키마 추출
         *     3. 이 API로 스키마 생성
         *
         *     ## 저장 경로
         *     `exports/{room_id}/component-schema.json`
         */
        post: operations["createRoomSchema"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rooms/{room_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 채팅 히스토리 조회
         * @description 채팅방의 메시지 히스토리를 페이지네이션하여 조회합니다.
         *
         *     ## Query Parameters
         *     - `limit`: 페이지당 메시지 수 (기본 20, 최대 100)
         *     - `cursor`: 페이지네이션 커서 (이전 응답의 next_cursor 값)
         *     - `order`: 정렬 순서 (desc: 최신순, asc: 오래된순)
         *
         *     ## 페이지네이션
         *     첫 요청 시 cursor 없이 호출하고, 다음 페이지는 응답의 `next_cursor` 값을 cursor로 전달합니다.
         *     `has_more`가 false면 마지막 페이지입니다.
         */
        get: operations["getRoomMessages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * AI 채팅 (Non-streaming)
         * @description 자연어로 UI를 설명하면 React TSX 코드를 생성합니다.
         *
         *     ## 요청 예시
         *     ```json
         *     {
         *       "message": "로그인 페이지 만들어줘",
         *       "room_id": "550e8400-e29b-41d4-a716-446655440000"
         *     }
         *     ```
         *
         *     ## 응답 구조
         *     - `message`: AI 원본 응답
         *     - `parsed.conversation`: 한국어 설명
         *     - `parsed.files`: 생성된 코드 파일 목록
         *     - `usage`: 토큰 사용량
         *
         *     ## room_id
         *     채팅방 ID (필수). 메시지가 해당 채팅방에 저장됩니다.
         *
         *     ## 스키마 모드
         *     채팅방의 schema_key가 설정되어 있으면 Firebase Storage에서 컴포넌트 스키마를 로드합니다.
         *     없으면 자유 모드(React + Tailwind CSS)로 동작합니다.
         *
         *     ## from_message_id (선택)
         *     특정 메시지의 코드를 기준으로 수정합니다. 해당 메시지까지의 컨텍스트를 사용하고, 그 메시지의 코드를 기반으로 AI가 수정합니다.
         *     ```json
         *     {
         *       "message": "버튼을 빨간색으로 바꿔줘",
         *       "room_id": "550e8400-e29b-41d4-a716-446655440000",
         *       "from_message_id": "886e7406-55f7-4582-9f4b-7a56ec4562d8"
         *     }
         *     ```
         */
        post: operations["chat_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * AI 채팅 (Streaming)
         * @description SSE(Server-Sent Events)를 통해 실시간 스트리밍 응답을 받습니다.
         *     이미지가 포함되면 Vision 모드로 동작합니다.
         *
         *     ## 요청 예시 (텍스트만)
         *     ```json
         *     {
         *       "message": "로그인 페이지 만들어줘",
         *       "room_id": "550e8400-e29b-41d4-a716-446655440000"
         *     }
         *     ```
         *
         *     ## 요청 예시 (이미지 포함 - Vision 모드)
         *     먼저 `/chat/images`로 이미지를 업로드한 후 URL을 사용합니다.
         *
         *     ```json
         *     {
         *       "message": "이 디자인을 React 코드로 만들어줘",
         *       "room_id": "550e8400-e29b-41d4-a716-446655440000",
         *       "image_urls": [
         *         "https://storage.googleapis.com/bucket/user_uploads/room-id/1234_uuid.png"
         *       ]
         *     }
         *     ```
         *
         *     ## 이벤트 타입
         *
         *     | 타입 | 설명 | 필드 |
         *     |------|------|------|
         *     | `start` | 스트리밍 시작 | `message_id` |
         *     | `chat` | 대화 텍스트 (실시간) | `text` |
         *     | `code` | 코드 파일 (완성 후) | `path`, `content` |
         *     | `done` | 스트리밍 완료 | `message_id` |
         *     | `error` | 오류 발생 | `error` |
         *
         *     ## SSE 응답 예시
         *     ```
         *     data: {"type": "start", "message_id": "abc-123-def"}
         *
         *     data: {"type": "chat", "text": "모던한 "}
         *
         *     data: {"type": "chat", "text": "로그인 페이지입니다."}
         *
         *     data: {"type": "code", "path": "src/pages/Login.tsx", "content": "import..."}
         *
         *     data: {"type": "done", "message_id": "abc-123-def"}
         *     ```
         *
         *     ## 제한 (Vision 모드)
         *     - 최대 5개 이미지
         *     - 지원 형식: JPEG, PNG, GIF, WebP
         *
         *     ## from_message_id (선택)
         *     특정 메시지의 코드를 기준으로 수정합니다. 해당 메시지까지의 컨텍스트를 사용하고, 그 메시지의 코드를 기반으로 AI가 수정합니다.
         *     ```json
         *     {
         *       "message": "버튼을 빨간색으로 바꿔줘",
         *       "room_id": "550e8400-e29b-41d4-a716-446655440000",
         *       "from_message_id": "886e7406-55f7-4582-9f4b-7a56ec4562d8"
         *     }
         *     ```
         */
        post: operations["chat_stream_chat_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 서버 상태 확인
         * @description 서버가 정상적으로 실행 중인지 확인합니다.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ChatRequest
         * @description 채팅 요청
         * @example {
         *       "message": "로그인 페이지 만들어줘",
         *       "room_id": "550e8400-e29b-41d4-a716-446655440000"
         *     }
         * @example {
         *       "message": "대시보드 만들어줘",
         *       "room_id": "550e8400-e29b-41d4-a716-446655440000"
         *     }
         * @example {
         *       "current_composition": {
         *         "instances": [
         *           {
         *             "component": "Button",
         *             "id": "button-1",
         *             "props": {
         *               "variant": "primary"
         *             }
         *           }
         *         ]
         *       },
         *       "message": "배경색을 파란색으로 바꿔줘",
         *       "room_id": "550e8400-e29b-41d4-a716-446655440000",
         *       "selected_instance_id": "button-1"
         *     }
         * @example {
         *       "from_message_id": "886e7406-55f7-4582-9f4b-7a56ec4562d8",
         *       "message": "버튼을 빨간색으로 바꿔줘",
         *       "room_id": "550e8400-e29b-41d4-a716-446655440000"
         *     }
         */
        ChatRequest: {
            /**
             * Message
             * @description 사용자 메시지 (최대 10,000자)
             * @example 로그인 페이지 만들어줘
             */
            message: string;
            /**
             * Room Id
             * @description 채팅방 ID
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            room_id: string;
            /**
             * Image Urls
             * @description Firebase Storage 이미지 URL 목록 (최대 5개) - Vision 모드 활성화
             * @example [
             *       "https://storage.googleapis.com/bucket/user_uploads/room-id/1234_uuid.png"
             *     ]
             */
            image_urls?: string[] | null;
            /**
             * Stream
             * @description 스트리밍 응답 여부 (True면 /stream 엔드포인트 사용 권장)
             * @default false
             */
            stream: boolean;
            /** @description 현재 렌더링된 컴포넌트 구조 (인스턴스 편집 모드용) */
            current_composition?: components["schemas"]["CurrentComposition"] | null;
            /**
             * Selected Instance Id
             * @description 사용자가 선택한 컴포넌트 인스턴스 ID (예: button-1)
             * @example button-1
             */
            selected_instance_id?: string | null;
            /**
             * From Message Id
             * @description 특정 메시지의 코드를 기준으로 수정 (해당 메시지까지의 컨텍스트 + 코드 기반 수정)
             * @example 886e7406-55f7-4582-9f4b-7a56ec4562d8
             */
            from_message_id?: string | null;
        };
        /**
         * ChatResponse
         * @description 채팅 응답 (Non-streaming)
         * @example {
         *       "message": {
         *         "content": "모던한 로그인 페이지입니다.\n\n<file path=\"src/pages/Login.tsx\">import { Button } from '@/components';\n\nconst Login = () => <Button>로그인</Button>;\n\nexport default Login;</file>",
         *         "role": "assistant"
         *       },
         *       "parsed": {
         *         "conversation": "모던한 로그인 페이지입니다.",
         *         "files": [
         *           {
         *             "content": "import { Button } from '@/components';\n\nconst Login = () => <Button>로그인</Button>;\n\nexport default Login;",
         *             "path": "src/pages/Login.tsx"
         *           }
         *         ],
         *         "raw": "..."
         *       },
         *       "usage": {
         *         "completion_tokens": 800,
         *         "prompt_tokens": 1500,
         *         "total_tokens": 2300
         *       }
         *     }
         */
        ChatResponse: {
            /** @description AI 응답 메시지 */
            message: components["schemas"]["Message"];
            /** @description 파싱된 응답 (conversation과 files 분리) */
            parsed?: components["schemas"]["ParsedResponse"] | null;
            /**
             * Usage
             * @description 토큰 사용량 정보
             * @example {
             *       "completion_tokens": 800,
             *       "prompt_tokens": 1500,
             *       "total_tokens": 2300
             *     }
             */
            usage?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * ComponentInstance
         * @description 컴포넌트 인스턴스 정보
         */
        ComponentInstance: {
            /**
             * Id
             * @description 인스턴스 ID (예: button-1, card-2)
             * @example button-1
             */
            id: string;
            /**
             * Component
             * @description 컴포넌트 이름
             * @example Button
             */
            component: string;
            /**
             * Props
             * @description 현재 props 값들
             * @example {
             *       "children": "로그인",
             *       "variant": "primary"
             *     }
             */
            props?: {
                [key: string]: unknown;
            };
        };
        /**
         * CreateRoomRequest
         * @description 채팅방 생성 요청
         * @example {
         *       "storybook_url": "https://storybook.example.com",
         *       "user_id": "user-123"
         *     }
         */
        CreateRoomRequest: {
            /**
             * User Id
             * @description 사용자 ID
             * @example user-123
             */
            user_id: string;
            /**
             * Storybook Url
             * @description Storybook URL (참고용)
             * @example https://storybook.example.com
             */
            storybook_url?: string | null;
        };
        /**
         * CreateSchemaRequest
         * @description 스키마 생성 요청
         */
        CreateSchemaRequest: {
            /**
             * Data
             * @description 컴포넌트 스키마 JSON
             */
            data: {
                [key: string]: unknown;
            };
        };
        /**
         * CreateSchemaResponse
         * @description 스키마 생성 응답
         */
        CreateSchemaResponse: {
            /**
             * Schema Key
             * @description Firebase Storage 경로
             */
            schema_key: string;
            /**
             * Component Count
             * @description 업로드된 컴포넌트 수
             */
            component_count: number;
            /**
             * Uploaded At
             * @description 업로드 시각 (ISO 8601)
             */
            uploaded_at: string;
        };
        /**
         * CurrentComposition
         * @description 현재 렌더링된 컴포넌트 구조
         */
        CurrentComposition: {
            /**
             * Instances
             * @description 렌더링된 컴포넌트 인스턴스 목록
             */
            instances?: components["schemas"]["ComponentInstance"][];
        };
        /**
         * FileContent
         * @description 생성된 파일 정보
         * @example {
         *       "content": "import { Button, Field } from '@/components';\n\nconst Login = () => {\n  return (\n    <div>\n      <Field label=\"이메일\" />\n      <Button>로그인</Button>\n    </div>\n  );\n};\n\nexport default Login;",
         *       "path": "src/pages/Login.tsx"
         *     }
         */
        FileContent: {
            /**
             * Path
             * @description 파일 경로 (예: src/pages/Login.tsx)
             * @example src/pages/Login.tsx
             */
            path: string;
            /**
             * Content
             * @description 파일 내용 (React TSX 코드)
             * @example import { Button } from '@/components';
             *
             *     const Login = () => {
             *       return <Button>로그인</Button>;
             *     };
             *
             *     export default Login;
             */
            content: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ImageUploadResponse
         * @description 이미지 업로드 응답
         */
        ImageUploadResponse: {
            /**
             * Url
             * @description 업로드된 이미지의 Firebase Storage URL
             * @example https://storage.googleapis.com/bucket/user_uploads/room-id/1234_uuid.png
             */
            url: string;
            /**
             * Path
             * @description Storage 내 파일 경로
             * @example user_uploads/room-id/1234_uuid.png
             */
            path: string;
        };
        /**
         * Message
         * @description 채팅 메시지
         * @example {
         *       "content": "로그인 페이지 만들어줘",
         *       "role": "user"
         *     }
         * @example {
         *       "content": "모던한 로그인 페이지입니다.\n\n<file path=\"src/pages/Login.tsx\">...</file>",
         *       "role": "assistant"
         *     }
         */
        Message: {
            /**
             * Role
             * @description 메시지 역할
             * @example user
             * @enum {string}
             */
            role: "user" | "assistant" | "system";
            /**
             * Content
             * @description 메시지 내용
             * @example 로그인 페이지 만들어줘
             */
            content: string;
        };
        /**
         * MessageDocument
         * @description 채팅 메시지 문서
         */
        MessageDocument: {
            /**
             * Id
             * @description 메시지 ID (UUID)
             */
            id: string;
            /**
             * Question
             * @description 사용자 질문
             * @default
             */
            question: string;
            /**
             * Text
             * @description AI 텍스트 응답
             * @default
             */
            text: string;
            /**
             * Content
             * @description React 코드 내용
             * @default
             */
            content: string;
            /**
             * Path
             * @description 파일 경로
             * @default
             */
            path: string;
            /**
             * Room Id
             * @description 채팅방 ID
             */
            room_id: string;
            /**
             * Question Created At
             * @description 질문 생성 시간 (ms timestamp)
             */
            question_created_at: number;
            /**
             * Answer Created At
             * @description 응답 생성 시간 (ms timestamp)
             */
            answer_created_at: number;
            /**
             * Status
             * @description 응답 상태
             * @enum {string}
             */
            status: "GENERATING" | "DONE" | "ERROR";
        };
        /**
         * PaginatedMessagesResponse
         * @description 페이지네이션된 메시지 응답
         */
        PaginatedMessagesResponse: {
            /**
             * Messages
             * @description 메시지 목록
             */
            messages: components["schemas"]["MessageDocument"][];
            /**
             * Next Cursor
             * @description 다음 페이지 커서 (answer_created_at)
             */
            next_cursor?: number | null;
            /**
             * Has More
             * @description 다음 페이지 존재 여부
             */
            has_more: boolean;
            /**
             * Total Count
             * @description 총 메시지 수
             */
            total_count: number;
        };
        /**
         * ParsedResponse
         * @description 파싱된 AI 응답 - 대화와 코드 파일 분리
         * @example {
         *       "conversation": "모던한 로그인 페이지입니다.",
         *       "files": [
         *         {
         *           "content": "import { Button } from '@/components';\n...",
         *           "path": "src/pages/Login.tsx"
         *         }
         *       ],
         *       "raw": "모던한 로그인 페이지입니다.\n\n<file path=\"src/pages/Login.tsx\">...</file>"
         *     }
         */
        ParsedResponse: {
            /**
             * Conversation
             * @description AI의 한국어 설명 (코드 외 텍스트)
             * @example 모던하고 깔끔한 로그인 페이지입니다. 그라데이션 배경과 카드 레이아웃을 사용했습니다.
             */
            conversation: string;
            /**
             * Files
             * @description 생성된 코드 파일 목록
             */
            files?: components["schemas"]["FileContent"][];
            /**
             * Raw
             * @description AI 원본 응답 (파싱 전)
             */
            raw: string;
        };
        /**
         * RoomResponse
         * @description 채팅방 응답
         */
        RoomResponse: {
            /**
             * Id
             * @description 채팅방 ID (UUID)
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            id: string;
            /**
             * Storybook Url
             * @description Storybook URL (참고용)
             * @example https://storybook.example.com
             */
            storybook_url?: string | null;
            /**
             * Schema Key
             * @description Firebase Storage 스키마 경로. None이면 자유 모드.
             * @example schemas/aplus-ui.json
             */
            schema_key?: string | null;
            /**
             * User Id
             * @description 사용자 ID
             * @example user-123
             */
            user_id: string;
            /**
             * Created At
             * @description 생성 시간 (ms timestamp)
             * @example 1736654400000
             */
            created_at: number;
        };
        /**
         * SchemaResponse
         * @description 스키마 조회 응답
         */
        SchemaResponse: {
            /** Schema Key */
            schema_key: string;
            /** Data */
            data: {
                [key: string]: unknown;
            };
        };
        /**
         * UpdateRoomRequest
         * @description 채팅방 업데이트 요청
         * @example {
         *       "schema_key": "schemas/aplus-ui.json",
         *       "storybook_url": "https://new-storybook.example.com"
         *     }
         */
        UpdateRoomRequest: {
            /**
             * Storybook Url
             * @description Storybook URL (참고용)
             * @example https://storybook.example.com
             */
            storybook_url?: string | null;
            /**
             * Schema Key
             * @description Firebase Storage 스키마 경로 변경
             * @example schemas/aplus-ui.json
             */
            schema_key?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createRoom: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRoomRequest"];
            };
        };
        responses: {
            /** @description 채팅방 생성 성공 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getRoom: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                room_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomResponse"];
                };
            };
            /** @description 채팅방을 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateRoom: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                room_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRoomRequest"];
            };
        };
        responses: {
            /** @description 업데이트 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomResponse"];
                };
            };
            /** @description 채팅방을 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    uploadRoomImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                room_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description 업로드할 이미지 파일
                     */
                    file: string;
                };
            };
        };
        responses: {
            /** @description 업로드 성공 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageUploadResponse"];
                };
            };
            /** @description 잘못된 요청 (파일 없음 등) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 채팅방을 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 파일 크기 초과 */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getRoomSchema: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                room_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchemaResponse"];
                };
            };
            /** @description 채팅방 또는 스키마를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    createRoomSchema: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                room_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSchemaRequest"];
            };
        };
        responses: {
            /** @description 생성 성공 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateSchemaResponse"];
                };
            };
            /** @description 잘못된 요청 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 채팅방을 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getRoomMessages: {
        parameters: {
            query?: {
                /** @description 페이지당 메시지 수 */
                limit?: number;
                /** @description 페이지네이션 커서 (answer_created_at) */
                cursor?: number | null;
                /** @description 정렬 순서 */
                order?: string;
            };
            header?: never;
            path: {
                room_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedMessagesResponse"];
                };
            };
            /** @description 채팅방을 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    chat_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description 잘못된 요청 (stream=true인 경우) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 채팅방을 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description AI API 호출 실패 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    chat_stream_chat_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description SSE 스트림 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    /**
                     * @example data: {"type": "chat", "text": "모던한 로그인"}
                     *
                     *     data: {"type": "done"}
                     */
                    "text/event-stream": unknown;
                };
            };
            /** @description 채팅방을 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description AI API 호출 실패 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 서버 정상 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "healthy"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
}
