"""
Firebase Shared Configuration

⚠️ AUTO-GENERATED - DO NOT EDIT MANUALLY
Generated by: scripts/generate-python.py
"""

from .collections import Collections
from .storage import StoragePaths

__all__ = ["Collections", "StoragePaths"]
