"""
Firebase Firestore Collection Names

⚠️ AUTO-GENERATED - DO NOT EDIT MANUALLY
Source: packages/shared-types/firebase/collections.json
Generated by: scripts/generate-python.py
"""


class Collections:
    """Firestore collection names"""

    CHAT_ROOMS = "chat_rooms"  # Chat room metadata
    CHAT_MESSAGES = "chat_messages"  # Individual messages within chat sessions
