"""
Firebase Firestore Collection Names and Document Types

⚠️ AUTO-GENERATED - DO NOT EDIT MANUALLY
Source: packages/shared-types/firebase/collections.json
Generated by: scripts/generate-python.py
"""

from typing import Literal, TypedDict
from typing_extensions import NotRequired


class Collections:
    """Firestore collection names"""

    CHAT_ROOMS = "chat_rooms"  # Chat room metadata
    CHAT_MESSAGES = "chat_messages"  # Chat messages within sessions
