"""
Database Table Names

⚠️ AUTO-GENERATED - DO NOT EDIT MANUALLY
Source: packages/shared-types/database/collections.json
Generated by: scripts/generate-python.py
"""


class Tables:
    """Database table names"""

    CHAT_ROOMS = "chat_rooms"  # Chat room metadata
    CHAT_MESSAGES = "chat_messages"  # Chat messages within sessions
