"""
Storage Paths

⚠️ AUTO-GENERATED - DO NOT EDIT MANUALLY
Source: packages/shared-types/database/storage.json
Generated by: scripts/generate-python.py
"""


class StoragePaths:
    """Storage path constants"""

    SCREENSHOTS = "screenshots"  # Component screenshots from Storybook
    ASSETS = "assets"  # Design system assets (icons, images)
    USER_UPLOADS = "user_uploads"  # User uploaded files
    EXPORTS = "exports"  # Generated export files (code, specs)
