"""
Database Document Types

⚠️ AUTO-GENERATED - DO NOT EDIT MANUALLY
Source: packages/shared-types/database/collections.json
Generated by: scripts/generate-python.py
"""

from typing import Literal, TypedDict


class ChatRoom(TypedDict):
    """
    Chat room metadata
    Collection: chat_rooms
    """

    id: str  # Chat room ID (UUID)
    storybook_url: str  # Storybook URL
    user_id: str  # User ID
    created_at: int  # Created timestamp (ms)

Status = Literal["GENERATING", "DONE", "ERROR"]



class ChatMessage(TypedDict):
    """
    Chat messages within sessions
    Collection: chat_messages
    """

    id: str  # Message ID (UUID)
    question: str  # User question
    text: str  # AI text response
    content: str  # React code content
    path: str  # File path
    room_id: str  # Chat room ID
    question_created_at: int  # Question timestamp (ms)
    answer_created_at: int  # Answer timestamp (ms)
    status: Status  # Response status
