/** @type {import('tailwindcss').Config} */
//  디자인 토큰 기반 TailwindCSS 프리셋
// aplus-cli에 의해 자동 생성된 파일입니다. 직접 수정하지 마세요.

module.exports = {
  theme: {
    extend: {
      fontSize: {
        'typography-body-lg-medium': ['18px', { lineHeight: '28px' }],
        'typography-body-lg-regular': ['18px', { lineHeight: '28px' }],
        'typography-body-md-medium': ['16px', { lineHeight: '24px' }],
        'typography-body-md-regular': ['16px', { lineHeight: '24px' }],
        'typography-body-sm-medium': ['14px', { lineHeight: '20px' }],
        'typography-body-sm-regular': ['14px', { lineHeight: '20px' }],
        'typography-button-lg-medium': ['18px', { lineHeight: '24px' }],
        'typography-button-md-medium': ['16px', { lineHeight: '20px' }],
        'typography-button-sm-medium': ['14px', { lineHeight: '20px' }],
        'typography-caption-sm-medium': ['14px', { lineHeight: '20px' }],
        'typography-caption-sm-regular': ['14px', { lineHeight: '20px' }],
        'typography-caption-xs-medium': ['14px', { lineHeight: '16px' }],
        'typography-caption-xs-regular': ['14px', { lineHeight: '16px' }],
        'typography-chart-axis-label-regular': ['14px', { lineHeight: '20px' }],
        'typography-chart-graph-label-medium-num': ['14px', { lineHeight: '20px' }],
        'typography-chart-legend-medium': ['14px', { lineHeight: '20px' }],
        'typography-chip-label-md-medium': ['14px', { lineHeight: '20px' }],
        'typography-chip-label-sm-medium': ['12px', { lineHeight: '16px' }],
        'typography-display-caption-lg-medium': ['18px', { lineHeight: '24px' }],
        'typography-display-caption-md-medium': ['16px', { lineHeight: '20px' }],
        'typography-display-indicator-md-medium': ['16px', { lineHeight: '20px' }],
        'typography-display-unit-lg-medium': ['18px', { lineHeight: '24px' }],
        'typography-display-value-xl-semibold-num': ['24px', { lineHeight: '32px' }],
        'typography-display-value-xxl-semibold-num': ['28px', { lineHeight: '36px' }],
        'typography-display-value-xxxl-bold-num': ['32px', { lineHeight: '40px' }],
        'typography-form-helper-text-md-regular': ['14px', { lineHeight: '20px' }],
        'typography-form-helper-text-sm-regular': ['12px', { lineHeight: '20px' }],
        'typography-form-label-md-medium': ['16px', { lineHeight: '24px' }],
        'typography-form-label-sm-medium': ['14px', { lineHeight: '20px' }],
        'typography-heading-lg-bold': ['24px', { lineHeight: '32px' }],
        'typography-heading-md-semibold': ['20px', { lineHeight: '28px' }],
        'typography-heading-xl-bold': ['28px', { lineHeight: '36px' }],
        'typography-navigation-menu-medium': ['14px', { lineHeight: '20px' }],
        'typography-navigation-menu-regular': ['14px', { lineHeight: '20px' }],
        'typography-table-caption-regular': ['14px', { lineHeight: '20px' }],
        'typography-table-cell-number-regular-num': ['16px', { lineHeight: '24px' }],
        'typography-table-cell-text-regular': ['16px', { lineHeight: '24px' }],
        'typography-table-header-medium': ['16px', { lineHeight: '24px' }]
      },
      colors: {
        'alert-error-bg': '#fae6e6',
        'alert-error-text': '#5f2120',
        'alert-info-bg': '#e1f1f9',
        'alert-info-text': '#014361',
        'alert-success-bg': '#e6efe6',
        'alert-success-text': '#1e4620',
        'alert-warning-bg': '#fdede1',
        'alert-warning-text': '#663c00',
        'badge-primary-solid-bg': '#0033a0',
        'badge-primary-subtle-bg': '#d9e2f5',
        'badge-primary-subtle-text': '#0033a0',
        'badge-solid-text': '#ffffff',
        'badge-status-error-subtle-bg': '#fae6e6',
        'badge-status-error-subtle-text': '#5f2120',
        'badge-status-info-subtle-bg': '#e1f1f9',
        'badge-status-info-subtle-text': '#014361',
        'badge-status-success-subtle-bg': '#e6efe6',
        'badge-status-success-subtle-text': '#1e4620',
        'badge-status-warning-subtle-bg': '#fdede1',
        'badge-status-warning-subtle-text': '#663c00',
        'bg-accent': '#0033a0',
        'bg-accent-secondary': '#98b3ee',
        'bg-accent-subtle': '#d9e2f5',
        'bg-canvas': '#f4f6f8',
        'bg-container-high': '#0000001e',
        'bg-container-low': '#0000000a',
        'bg-container-medium': '#00000014',
        'bg-disabled-on-filled': '#ced4da',
        'bg-disabled-on-light': '#eceff3',
        'bg-selection': '#ecf0fa',
        'bg-semantic-error': '#d32f2f',
        'bg-semantic-error-subtle': '#fae6e6',
        'bg-semantic-info': '#0288d1',
        'bg-semantic-info-subtle': '#e1f1f9',
        'bg-semantic-success': '#2e7d32',
        'bg-semantic-success-subtle': '#e6efe6',
        'bg-semantic-warning': '#ed6c02',
        'bg-semantic-warning-subtle': '#fdede1',
        'bg-subtle': '#eceff3',
        'bg-surface': '#ffffff',
        'bg-text-selection': '#d0dbf2',
        'border-accent': '#0033a0',
        'border-contrast': '#ffffff',
        'border-default': '#dee2e6',
        'border-disabled': '#dee2e6',
        'border-selection': '#0033a0',
        'border-semantic-error': '#d32f2f',
        'border-semantic-info': '#0288d1',
        'border-semantic-success': '#2e7d32',
        'border-semantic-warning': '#ed6c02',
        'border-strong': '#ced4da',
        'border-subtle': '#e9ecef',
        'brand-blue-100': '#c3d6ff',
        'brand-blue-200': '#98b3ee',
        'brand-blue-300': '#698fe0',
        'brand-blue-400': '#3e6ccf',
        'brand-blue-50': '#e1eaff',
        'brand-blue-500': '#154cc1',
        'brand-blue-600': '#0033a0',
        'brand-blue-700': '#002480',
        'brand-blue-800': '#001d63',
        'brand-blue-900': '#00154a',
        'brand-primary': '#0033a0',
        'brand-primary-hover': '#154cc1',
        'brand-primary-pressed': '#002480',
        'brand-secondary': '#98b3ee',
        'brand-secondary-hover': '#698fe0',
        'brand-secondary-pressed': '#3e6ccf',
        'brand-selection-hover': '#e2e9f7',
        'brand-selection-pressed': '#d9e2f5',
        'chart-axis-line': '#dee2e6',
        'chart-label': '#343a40',
        'chart-label-inverse': '#ffffff',
        'chart-series-1': '#0033a0',
        'chart-series-2': '#3e6ccf',
        'chart-series-3': '#98b3ee',
        'chart-series-4': '#698fe0',
        'chart-series-5': '#9da4ab',
        'chart-series-6': '#6c757d',
        'chart-series-line': '#00154a',
        'chip-bg-disabled': '#eceff3',
        'chip-bg-off': '#eceff3',
        'chip-bg-selected': '#ecf0fa',
        'control-bg-disabled': '#ced4da',
        'control-bg-off': '#ced4da',
        'control-bg-on': '#0033a0',
        'control-icon-disabled': '#9da4ab',
        'control-icon-on': '#ffffff',
        'control-icon-selected': '#0033a0',
        'control-knob-disabled': '#eceff3',
        'control-knob-off': '#ffffff',
        'control-knob-on': '#ffffff',
        'control-stroke-default': '#ced4da',
        'control-stroke-disabled': '#dee2e6',
        'field-bg-disabled': '#eceff3',
        'field-bg-filled': '#0000000a',
        'field-bg-readonly': '#eceff3',
        'field-bg-surface': '#ffffff',
        'field-border-default': '#dee2e6',
        'field-border-disabled': '#dee2e6',
        'field-border-error': '#d32f2f',
        'field-border-focus': '#0033a0',
        'field-border-success': '#2e7d32',
        'field-border-warning': '#ed6c02',
        'field-caret': '#0033a0',
        'field-text-help': '#495057',
        'field-text-placeholder': '#6c757d',
        'focus': '#0033a0',
        'hue-cyan-300': '#69d3e5',
        'hue-cyan-500': '#06b6d4',
        'hue-cyan-800': '#155e75',
        'hue-green-300': '#7adc9e',
        'hue-green-500': '#22c55e',
        'hue-green-800': '#166534',
        'hue-lime-300': '#b5e073',
        'hue-lime-500': '#84cc16',
        'hue-lime-800': '#3f6212',
        'hue-orange-300': '#fbab73',
        'hue-orange-500': '#f97316',
        'hue-orange-800': '#9a3412',
        'hue-pink-300': '#f391c1',
        'hue-pink-500': '#ec4899',
        'hue-pink-800': '#9d174d',
        'hue-red-300': '#f58e8e',
        'hue-red-500': '#ef4444',
        'hue-red-800': '#991b1b',
        'hue-violet-300': '#b99df9',
        'hue-violet-500': '#8b5cf6',
        'hue-violet-800': '#5b21b6',
        'hue-yellow-300': '#f2d16a',
        'hue-yellow-500': '#eab308',
        'hue-yellow-800': '#854d0e',
        'icon-decorative-accent': '#0033a0',
        'icon-decorative-default': '#495057',
        'icon-decorative-tertiary': '#6c757d',
        'icon-interactive-default': '#495057',
        'icon-interactive-disabled': '#9da4ab',
        'icon-interactive-inverse': '#ffffff',
        'icon-interactive-on-secondary': '#212529',
        'icon-interactive-on-selection': '#0033a0',
        'icon-semantic-error': '#d32f2f',
        'icon-semantic-info': '#0288d1',
        'icon-semantic-success': '#2e7d32',
        'icon-semantic-warning': '#ed6c02',
        'neutral-gray-0': '#ffffff',
        'neutral-gray-100': '#f4f6f8',
        'neutral-gray-1000': '#000000',
        'neutral-gray-150': '#eceff3',
        'neutral-gray-200': '#e9ecef',
        'neutral-gray-300': '#dee2e6',
        'neutral-gray-400': '#ced4da',
        'neutral-gray-450': '#bfc5cc',
        'neutral-gray-50': '#f9fafb',
        'neutral-gray-500': '#9da4ab',
        'neutral-gray-600': '#6c757d',
        'neutral-gray-700': '#495057',
        'neutral-gray-800': '#343a40',
        'neutral-gray-900': '#212529',
        'overlay-gray-1000-00': '#00000000',
        'overlay-gray-1000-04': '#0000000a',
        'overlay-gray-1000-06': '#0000000f',
        'overlay-gray-1000-08': '#00000014',
        'overlay-gray-1000-10': '#00000019',
        'overlay-gray-1000-12': '#0000001e',
        'overlay-gray-1000-56': '#0000008e',
        'overlay-scrim': '#0000008e',
        'overlay-transparent': '#00000000',
        'overlay-white-0-08': '#ffffff1e',
        'overlay-white-0-16': '#ffffff28',
        'segment-group-bg': '#ffffff',
        'segment-item-bg-selected': '#ecf0fa',
        'semantic-error': '#d32f2f',
        'semantic-error-500': '#d32f2f',
        'semantic-error-700': '#5f2120',
        'semantic-info': '#0288d1',
        'semantic-info-500': '#0288d1',
        'semantic-info-700': '#014361',
        'semantic-success': '#2e7d32',
        'semantic-success-500': '#2e7d32',
        'semantic-success-700': '#1e4620',
        'semantic-warning': '#ed6c02',
        'semantic-warning-500': '#ed6c02',
        'semantic-warning-700': '#663c00',
        'state-overlay-on-colored-hover': '#00000014',
        'state-overlay-on-colored-pressed': '#0000001e',
        'state-overlay-on-inverse-hover': '#ffffff1e',
        'state-overlay-on-inverse-pressed': '#ffffff28',
        'state-overlay-on-neutral-hover': '#0000000f',
        'state-overlay-on-neutral-pressed': '#00000019',
        'tag-default-bg': '#eceff3',
        'tag-default-text': '#212529',
        'tag-more-bg': '#ffffff',
        'tag-more-border': '#dee2e6',
        'text-accent': '#0033a0',
        'text-disabled': '#9da4ab',
        'text-inverse': '#ffffff',
        'text-on-selection': '#0033a0',
        'text-primary': '#212529',
        'text-secondary': '#495057',
        'text-semantic-error': '#d32f2f',
        'text-semantic-info': '#0288d1',
        'text-semantic-on-error': '#5f2120',
        'text-semantic-on-info': '#014361',
        'text-semantic-on-success': '#1e4620',
        'text-semantic-on-warning': '#663c00',
        'text-tertiary': '#6c757d',
        'tint-brand-primary-500-08': '#ecf0fa',
        'tint-brand-primary-500-12': '#e2e9f7',
        'tint-brand-primary-500-16': '#d9e2f5',
        'tint-brand-primary-500-20': '#d0dbf2',
        'tint-cyan-500-12': '#e1f6fa',
        'tint-error-500-08': '#fbeeee',
        'tint-error-500-12': '#fae6e6',
        'tint-error-500-16': '#f8dede',
        'tint-green-500-12': '#e4f8ec',
        'tint-info-500-08': '#ebf5fb',
        'tint-info-500-12': '#e1f1f9',
        'tint-info-500-16': '#d7ecf8',
        'tint-lime-500-12': '#f0f9e3',
        'tint-orange-500-12': '#feeee3',
        'tint-pink-500-12': '#fde9f3',
        'tint-red-500-12': '#fde9e9',
        'tint-success-500-08': '#eef5ef',
        'tint-success-500-12': '#e6efe6',
        'tint-success-500-16': '#deeade',
        'tint-violet-500-12': '#f1ebfe',
        'tint-warning-500-08': '#fef3eb',
        'tint-warning-500-12': '#fdede1',
        'tint-warning-500-16': '#fce7d7',
        'tint-yellow-500-12': '#fcf6e1'
      },
      spacing: {
        'component-gap-article-items-md': '24px',
        'component-gap-article-items-md-compact': '20px',
        'component-gap-article-items-sm': '12px',
        'component-gap-article-items-sm-compact': '10px',
        'component-gap-breadcrumb': '0px',
        'component-gap-breadcrumb-compact': '0px',
        'component-gap-chip-group': '6px',
        'component-gap-chip-group-compact': '6px',
        'component-gap-content-lg': '16px',
        'component-gap-content-lg-compact': '12px',
        'component-gap-content-md': '12px',
        'component-gap-content-md-compact': '8px',
        'component-gap-content-sm': '8px',
        'component-gap-content-sm-compact': '6px',
        'component-gap-content-xl': '24px',
        'component-gap-content-xl-compact': '16px',
        'component-gap-content-xs': '4px',
        'component-gap-content-xs-compact': '2px',
        'component-gap-control-group': '8px',
        'component-gap-control-group-compact': '6px',
        'component-gap-dialog-items': '16px',
        'component-gap-dialog-items-compact': '16px',
        'component-gap-dialog-structure': '16px',
        'component-gap-dialog-structure-compact': '16px',
        'component-gap-field-group-x': '16px',
        'component-gap-field-group-x-compact': '12px',
        'component-gap-field-group-y': '12px',
        'component-gap-field-group-y-compact': '12px',
        'component-gap-filterbar-items': '12px',
        'component-gap-filterbar-items-compact': '12px',
        'component-gap-icon-label-md': '8px',
        'component-gap-icon-label-md-compact': '8px',
        'component-gap-icon-label-sm': '6px',
        'component-gap-icon-label-sm-compact': '6px',
        'component-gap-icon-label-xs': '4px',
        'component-gap-icon-label-xs-compact': '4px',
        'component-gap-input-group': '6px',
        'component-gap-input-group-compact': '6px',
        'component-gap-overlay-anchor-md': '8px',
        'component-gap-overlay-anchor-md-compact': '8px',
        'component-gap-overlay-anchor-sm': '4px',
        'component-gap-overlay-anchor-sm-compact': '4px',
        'component-gap-tab-group': '12px',
        'component-gap-tab-group-compact': '12px',
        'component-gap-tag-group': '4px',
        'component-gap-tag-group-compact': '4px',
        'component-inset-alert-inline-x': '16px',
        'component-inset-alert-inline-x-compact': '14px',
        'component-inset-alert-inline-y': '12px',
        'component-inset-alert-inline-y-compact': '10px',
        'component-inset-alert-toast-x': '20px',
        'component-inset-alert-toast-x-compact': '16px',
        'component-inset-alert-toast-y': '16px',
        'component-inset-alert-toast-y-compact': '14px',
        'component-inset-button-lg-x': '16px',
        'component-inset-button-lg-x-compact': '16px',
        'component-inset-button-md-x': '14px',
        'component-inset-button-md-x-compact': '14px',
        'component-inset-button-sm-x': '12px',
        'component-inset-button-sm-x-compact': '12px',
        'component-inset-button-y': '8px',
        'component-inset-button-y-compact': '6px',
        'component-inset-card-x': '20px',
        'component-inset-card-x-compact': '20px',
        'component-inset-card-y': '20px',
        'component-inset-card-y-compact': '20px',
        'component-inset-chip-with-icon-x': '10px',
        'component-inset-chip-with-icon-x-compact': '10px',
        'component-inset-chip-x': '12px',
        'component-inset-chip-x-compact': '12px',
        'component-inset-chip-y': '6px',
        'component-inset-chip-y-compact': '6px',
        'component-inset-dialog-x': '32px',
        'component-inset-dialog-x-compact': '32px',
        'component-inset-dialog-y': '32px',
        'component-inset-dialog-y-compact': '32px',
        'component-inset-divider-bottom': '8px',
        'component-inset-divider-bottom-compact': '6px',
        'component-inset-divider-x': '8px',
        'component-inset-divider-x-compact': '6px',
        'component-inset-filterbar-x': '16px',
        'component-inset-filterbar-x-compact': '16px',
        'component-inset-filterbar-y': '16px',
        'component-inset-filterbar-y-compact': '16px',
        'component-inset-footer-x': '24px',
        'component-inset-footer-x-compact': '24px',
        'component-inset-footer-y': '12px',
        'component-inset-footer-y-compact': '8px',
        'component-inset-header-items-x': '24px',
        'component-inset-header-items-x-compact': '24px',
        'component-inset-header-items-y': '8px',
        'component-inset-header-items-y-compact': '8px',
        'component-inset-input-editor-x': '32px',
        'component-inset-input-editor-x-compact': '32px',
        'component-inset-input-editor-y': '40px',
        'component-inset-input-editor-y-compact': '40px',
        'component-inset-input-multiline-y': '10px',
        'component-inset-input-multiline-y-compact': '10px',
        'component-inset-input-x': '12px',
        'component-inset-input-x-compact': '12px',
        'component-inset-input-y': '6px',
        'component-inset-input-y-compact': '6px',
        'component-inset-item-x': '12px',
        'component-inset-item-x-compact': '12px',
        'component-inset-item-y': '8px',
        'component-inset-item-y-compact': '6px',
        'component-inset-list-x': '12px',
        'component-inset-list-x-compact': '12px',
        'component-inset-list-y': '12px',
        'component-inset-list-y-compact': '8px',
        'component-inset-menu-divider-y': '4px',
        'component-inset-menu-divider-y-compact': '4px',
        'component-inset-menu-item-x': '16px',
        'component-inset-menu-item-x-compact': '16px',
        'component-inset-menu-item-y': '12px',
        'component-inset-menu-item-y-compact': '10px',
        'component-inset-menu-x': '4px',
        'component-inset-menu-x-compact': '4px',
        'component-inset-menu-y': '4px',
        'component-inset-menu-y-compact': '4px',
        'component-inset-optical-bottom': '8px',
        'component-inset-optical-bottom-compact': '4px',
        'component-inset-optical-left': '8px',
        'component-inset-optical-left-compact': '4px',
        'component-inset-optical-right': '8px',
        'component-inset-optical-right-compact': '4px',
        'component-inset-optical-top': '8px',
        'component-inset-optical-top-compact': '4px',
        'component-inset-page-x': '24px',
        'component-inset-page-x-compact': '24px',
        'component-inset-panel-x': '24px',
        'component-inset-panel-x-compact': '24px',
        'component-inset-panel-y': '20px',
        'component-inset-panel-y-compact': '16px',
        'component-inset-pill-with-icon-x': '6px',
        'component-inset-pill-with-icon-x-compact': '6px',
        'component-inset-pill-x': '8px',
        'component-inset-pill-x-compact': '8px',
        'component-inset-pill-y': '2px',
        'component-inset-pill-y-compact': '2px',
        'component-inset-popover-x': '12px',
        'component-inset-popover-x-compact': '10px',
        'component-inset-popover-y': '10px',
        'component-inset-popover-y-compact': '8px',
        'component-inset-post-x': '32px',
        'component-inset-post-x-compact': '32px',
        'component-inset-post-y': '32px',
        'component-inset-post-y-compact': '32px',
        'component-inset-section-x': '24px',
        'component-inset-section-x-compact': '20px',
        'component-inset-section-y': '20px',
        'component-inset-section-y-compact': '16px',
        'component-inset-segment-group-xy': '2px',
        'component-inset-segment-group-xy-compact': '2px',
        'component-inset-segment-item-lg-x': '14px',
        'component-inset-segment-item-lg-x-compact': '14px',
        'component-inset-segment-item-md-x': '12px',
        'component-inset-segment-item-md-x-compact': '12px',
        'component-inset-segment-item-sm-x': '10px',
        'component-inset-segment-item-sm-x-compact': '10px',
        'component-inset-segment-item-y': '6px',
        'component-inset-segment-item-y-compact': '6px',
        'component-inset-tab-x': '12px',
        'component-inset-tab-x-compact': '12px',
        'component-inset-tab-y': '8px',
        'component-inset-tab-y-compact': '8px',
        'component-inset-table-cell-x': '12px',
        'component-inset-table-cell-x-compact': '10px',
        'component-inset-table-cell-y': '10px',
        'component-inset-table-cell-y-compact': '8px',
        'component-inset-table-x': '24px',
        'component-inset-table-x-compact': '24px',
        'component-inset-table-y': '16px',
        'component-inset-table-y-compact': '16px',
        'component-inset-toolbar-x': '24px',
        'component-inset-toolbar-x-compact': '24px',
        'component-inset-toolbar-y': '8px',
        'component-inset-toolbar-y-compact': '6px',
        'component-inset-tooltip-x': '12px',
        'component-inset-tooltip-x-compact': '12px',
        'component-inset-tooltip-y': '8px',
        'component-inset-tooltip-y-compact': '8px',
        'layout-gutter': '20px',
        'layout-gutter-compact': '20px',
        'layout-inline-lg': '12px',
        'layout-inline-lg-compact': '12px',
        'layout-inline-lg2': '16px',
        'layout-inline-lg2-compact': '16px',
        'layout-inline-md': '8px',
        'layout-inline-md-compact': '8px',
        'layout-inline-sm': '6px',
        'layout-inline-sm-compact': '6px',
        'layout-inline-xl': '20px',
        'layout-inline-xl-compact': '20px',
        'layout-inline-xl2': '24px',
        'layout-inline-xl2-compact': '24px',
        'layout-inline-xs': '4px',
        'layout-inline-xs-compact': '4px',
        'layout-inline-xxl': '32px',
        'layout-inline-xxl-compact': '32px',
        'layout-inline-xxxl': '40px',
        'layout-inline-xxxl-compact': '40px',
        'layout-stack-lg': '20px',
        'layout-stack-lg-compact': '20px',
        'layout-stack-lg2': '24px',
        'layout-stack-lg2-compact': '24px',
        'layout-stack-md': '12px',
        'layout-stack-md-compact': '12px',
        'layout-stack-md2': '16px',
        'layout-stack-md2-compact': '16px',
        'layout-stack-sm': '8px',
        'layout-stack-sm-compact': '8px',
        'layout-stack-xl': '32px',
        'layout-stack-xl-compact': '32px',
        'layout-stack-xs': '4px',
        'layout-stack-xs-compact': '4px',
        'layout-stack-xxl': '40px',
        'layout-stack-xxl-compact': '40px',
        'layout-stack-xxxl': '48px',
        'layout-stack-xxxl-compact': '48px'
      },
      fontWeight: {
        'typography-body-lg-medium': 500,
        'typography-body-lg-regular': 400,
        'typography-body-md-medium': 500,
        'typography-body-md-regular': 400,
        'typography-body-sm-medium': 500,
        'typography-body-sm-regular': 400,
        'typography-button-lg-medium': 500,
        'typography-button-md-medium': 500,
        'typography-button-sm-medium': 500,
        'typography-caption-sm-medium': 500,
        'typography-caption-sm-regular': 400,
        'typography-caption-xs-medium': 500,
        'typography-caption-xs-regular': 400,
        'typography-chart-axis-label-regular': 400,
        'typography-chart-graph-label-medium-num': 500,
        'typography-chart-legend-medium': 500,
        'typography-chip-label-md-medium': 500,
        'typography-chip-label-sm-medium': 500,
        'typography-display-caption-lg-medium': 500,
        'typography-display-caption-md-medium': 500,
        'typography-display-indicator-md-medium': 500,
        'typography-display-unit-lg-medium': 500,
        'typography-display-value-xl-semibold-num': 600,
        'typography-display-value-xxl-semibold-num': 600,
        'typography-display-value-xxxl-bold-num': 700,
        'typography-form-helper-text-md-regular': 400,
        'typography-form-helper-text-sm-regular': 400,
        'typography-form-label-md-medium': 500,
        'typography-form-label-sm-medium': 500,
        'typography-heading-lg-bold': 700,
        'typography-heading-md-semibold': 600,
        'typography-heading-xl-bold': 700,
        'typography-navigation-menu-medium': 500,
        'typography-navigation-menu-regular': 400,
        'typography-table-caption-regular': 400,
        'typography-table-cell-number-regular-num': 400,
        'typography-table-cell-text-regular': 400,
        'typography-table-header-medium': 500
      },
      fontFamily: {
        'typography-body-lg-medium': ['Pretendard', 'sans-serif'],
        'typography-body-lg-regular': ['Pretendard', 'sans-serif'],
        'typography-body-md-medium': ['Pretendard', 'sans-serif'],
        'typography-body-md-regular': ['Pretendard', 'sans-serif'],
        'typography-body-sm-medium': ['Pretendard', 'sans-serif'],
        'typography-body-sm-regular': ['Pretendard', 'sans-serif'],
        'typography-button-lg-medium': ['Pretendard', 'sans-serif'],
        'typography-button-md-medium': ['Pretendard', 'sans-serif'],
        'typography-button-sm-medium': ['Pretendard', 'sans-serif'],
        'typography-caption-sm-medium': ['Pretendard', 'sans-serif'],
        'typography-caption-sm-regular': ['Pretendard', 'sans-serif'],
        'typography-caption-xs-medium': ['Pretendard', 'sans-serif'],
        'typography-caption-xs-regular': ['Pretendard', 'sans-serif'],
        'typography-chart-axis-label-regular': ['Pretendard', 'sans-serif'],
        'typography-chart-graph-label-medium-num': ['Pretendard', 'sans-serif'],
        'typography-chart-legend-medium': ['Pretendard', 'sans-serif'],
        'typography-chip-label-md-medium': ['Pretendard', 'sans-serif'],
        'typography-chip-label-sm-medium': ['Pretendard', 'sans-serif'],
        'typography-display-caption-lg-medium': ['Pretendard', 'sans-serif'],
        'typography-display-caption-md-medium': ['Pretendard', 'sans-serif'],
        'typography-display-indicator-md-medium': ['Pretendard', 'sans-serif'],
        'typography-display-unit-lg-medium': ['Pretendard', 'sans-serif'],
        'typography-display-value-xl-semibold-num': ['Pretendard', 'sans-serif'],
        'typography-display-value-xxl-semibold-num': ['Pretendard', 'sans-serif'],
        'typography-display-value-xxxl-bold-num': ['Pretendard', 'sans-serif'],
        'typography-form-helper-text-md-regular': ['Pretendard', 'sans-serif'],
        'typography-form-helper-text-sm-regular': ['Pretendard', 'sans-serif'],
        'typography-form-label-md-medium': ['Pretendard', 'sans-serif'],
        'typography-form-label-sm-medium': ['Pretendard', 'sans-serif'],
        'typography-heading-lg-bold': ['Pretendard', 'sans-serif'],
        'typography-heading-md-semibold': ['Pretendard', 'sans-serif'],
        'typography-heading-xl-bold': ['Pretendard', 'sans-serif'],
        'typography-navigation-menu-medium': ['Pretendard', 'sans-serif'],
        'typography-navigation-menu-regular': ['Pretendard', 'sans-serif'],
        'typography-table-caption-regular': ['Pretendard', 'sans-serif'],
        'typography-table-cell-number-regular-num': ['Pretendard', 'sans-serif'],
        'typography-table-cell-text-regular': ['Pretendard', 'sans-serif'],
        'typography-table-header-medium': ['Pretendard', 'sans-serif']
      },
    },
  },
  plugins: [
    require('tailwindcss/plugin')(function({ addUtilities }) {
      const newUtilities = {
        '.text-body-lg-medium': {
          fontSize: '18px',
          lineHeight: '28px',
          fontWeight: '500',
        },
        '.text-body-lg-regular': {
          fontSize: '18px',
          lineHeight: '28px',
          fontWeight: '400',
        },
        '.text-body-md-medium': {
          fontSize: '16px',
          lineHeight: '24px',
          fontWeight: '500',
        },
        '.text-body-md-regular': {
          fontSize: '16px',
          lineHeight: '24px',
          fontWeight: '400',
        },
        '.text-body-sm-medium': {
          fontSize: '14px',
          lineHeight: '20px',
          fontWeight: '500',
        },
        '.text-body-sm-regular': {
          fontSize: '14px',
          lineHeight: '20px',
          fontWeight: '400',
        },
        '.text-button-lg-medium': {
          fontSize: '18px',
          lineHeight: '24px',
          fontWeight: '500',
        },
        '.text-button-md-medium': {
          fontSize: '16px',
          lineHeight: '20px',
          fontWeight: '500',
        },
        '.text-button-sm-medium': {
          fontSize: '14px',
          lineHeight: '20px',
          fontWeight: '500',
        },
        '.text-caption-sm-medium': {
          fontSize: '14px',
          lineHeight: '20px',
          fontWeight: '500',
        },
        '.text-caption-sm-regular': {
          fontSize: '14px',
          lineHeight: '20px',
          fontWeight: '400',
        },
        '.text-caption-xs-medium': {
          fontSize: '14px',
          lineHeight: '16px',
          fontWeight: '500',
        },
        '.text-caption-xs-regular': {
          fontSize: '14px',
          lineHeight: '16px',
          fontWeight: '400',
        },
        '.text-chart-axis-label-regular': {
          fontSize: '14px',
          lineHeight: '20px',
          fontWeight: '400',
        },
        '.text-chart-graph-label-medium-num': {
          fontSize: '14px',
          lineHeight: '20px',
          fontWeight: '500',
        },
        '.text-chart-legend-medium': {
          fontSize: '14px',
          lineHeight: '20px',
          fontWeight: '500',
        },
        '.text-chip-label-md-medium': {
          fontSize: '14px',
          lineHeight: '20px',
          fontWeight: '500',
        },
        '.text-chip-label-sm-medium': {
          fontSize: '12px',
          lineHeight: '16px',
          fontWeight: '500',
        },
        '.text-display-caption-lg-medium': {
          fontSize: '18px',
          lineHeight: '24px',
          fontWeight: '500',
        },
        '.text-display-caption-md-medium': {
          fontSize: '16px',
          lineHeight: '20px',
          fontWeight: '500',
        },
        '.text-display-indicator-md-medium': {
          fontSize: '16px',
          lineHeight: '20px',
          fontWeight: '500',
        },
        '.text-display-unit-lg-medium': {
          fontSize: '18px',
          lineHeight: '24px',
          fontWeight: '500',
        },
        '.text-display-value-xl-semibold-num': {
          fontSize: '24px',
          lineHeight: '32px',
          fontWeight: '600',
        },
        '.text-display-value-xxl-semibold-num': {
          fontSize: '28px',
          lineHeight: '36px',
          fontWeight: '600',
        },
        '.text-display-value-xxxl-bold-num': {
          fontSize: '32px',
          lineHeight: '40px',
          fontWeight: '700',
        },
        '.text-form-helper-text-md-regular': {
          fontSize: '14px',
          lineHeight: '20px',
          fontWeight: '400',
        },
        '.text-form-helper-text-sm-regular': {
          fontSize: '12px',
          lineHeight: '20px',
          fontWeight: '400',
        },
        '.text-form-label-md-medium': {
          fontSize: '16px',
          lineHeight: '24px',
          fontWeight: '500',
        },
        '.text-form-label-sm-medium': {
          fontSize: '14px',
          lineHeight: '20px',
          fontWeight: '500',
        },
        '.text-heading-lg-bold': {
          fontSize: '24px',
          lineHeight: '32px',
          fontWeight: '700',
        },
        '.text-heading-md-semibold': {
          fontSize: '20px',
          lineHeight: '28px',
          fontWeight: '600',
        },
        '.text-heading-xl-bold': {
          fontSize: '28px',
          lineHeight: '36px',
          fontWeight: '700',
        },
        '.text-navigation-menu-medium': {
          fontSize: '14px',
          lineHeight: '20px',
          fontWeight: '500',
        },
        '.text-navigation-menu-regular': {
          fontSize: '14px',
          lineHeight: '20px',
          fontWeight: '400',
        },
        '.text-table-caption-regular': {
          fontSize: '14px',
          lineHeight: '20px',
          fontWeight: '400',
        },
        '.text-table-cell-number-regular-num': {
          fontSize: '16px',
          lineHeight: '24px',
          fontWeight: '400',
        },
        '.text-table-cell-text-regular': {
          fontSize: '16px',
          lineHeight: '24px',
          fontWeight: '400',
        },
        '.text-table-header-medium': {
          fontSize: '16px',
          lineHeight: '24px',
          fontWeight: '500',
        },
      };
      addUtilities(newUtilities);
    })
  ],
};
