/**
 * Firebase Firestore Collection Names and Document Types
 *
 * ⚠️ AUTO-GENERATED - DO NOT EDIT MANUALLY
 * Source: packages/shared-types/firebase/collections.json
 * Generated by: scripts/generate-typescript.js
 */

export const COLLECTIONS = {
  CHAT_ROOMS: 'chat_rooms',
  CHAT_MESSAGES: 'chat_messages'
} as const;

export type CollectionName = typeof COLLECTIONS[keyof typeof COLLECTIONS];


