/**
 * Firebase Firestore Document Types
 *
 * ⚠️ AUTO-GENERATED - DO NOT EDIT MANUALLY
 * Source: packages/shared-types/firebase/collections.json
 * Generated by: scripts/generate-typescript.js
 */

/**
 * Response status
 */
export type Status = 'GENERATING' | 'DONE' | 'ERROR';

/**
 * Chat room metadata
 * Collection: chat_rooms
 */
export interface ChatRoom {
  /** Chat room ID (UUID) */
  id: string;
  /** Storybook URL */
  storybook_url: string;
  /** User ID */
  user_id: string;
  /** Created timestamp (ms) */
  created_at: number;
}

/**
 * Chat messages within sessions
 * Collection: chat_messages
 */
export interface ChatMessage {
  /** Message ID (UUID) */
  id: string;
  /** User question */
  question: string;
  /** AI text response */
  text: string;
  /** React code content */
  content: string;
  /** File path */
  path: string;
  /** Chat room ID */
  room_id: string;
  /** Question timestamp (ms) */
  question_created_at: number;
  /** Answer timestamp (ms) */
  answer_created_at: number;
  /** Response status */
  status: Status;
}
