/**
 * Database Table Names and Document Types
 *
 * ⚠️ AUTO-GENERATED - DO NOT EDIT MANUALLY
 * Source: packages/shared-types/database/collections.json
 * Generated by: scripts/generate-typescript.js
 */

export const TABLES = {
  CHAT_ROOMS: 'chat_rooms',
  CHAT_MESSAGES: 'chat_messages'
} as const;

export type TableName = typeof TABLES[keyof typeof TABLES];

