/**
 * Storage Paths
 *
 * ⚠️ AUTO-GENERATED - DO NOT EDIT MANUALLY
 * Source: packages/shared-types/database/storage.json
 * Generated by: scripts/generate-typescript.js
 */

export const STORAGE_PATHS = {
  SCREENSHOTS: 'screenshots',
  ASSETS: 'assets',
  USER_UPLOADS: 'user_uploads',
  EXPORTS: 'exports'
} as const;

export type StoragePath = typeof STORAGE_PATHS[keyof typeof STORAGE_PATHS];
