/**
 * Database Document Types
 *
 * ⚠️ AUTO-GENERATED - DO NOT EDIT MANUALLY
 * Source: packages/shared-types/database/collections.json
 * Generated by: scripts/generate-typescript.js
 */

/**
 * Response status
 */
export type Status = 'GENERATING' | 'DONE' | 'ERROR';

/**
 * Chat room metadata
 * Collection: chat_rooms
 */
export interface ChatRoom {
  /** Chat room ID (UUID) */
  id: string;
  /** Storybook URL */
  storybook_url: string;
  /** User ID */
  user_id: string;
  /** Created timestamp (ms) */
  created_at: number;
}

/**
 * Chat messages within sessions
 * Collection: chat_messages
 */
export interface ChatMessage {
  /** Message ID (UUID) */
  id: string;
  /** User question */
  question: string;
  /** AI text response */
  text: string;
  /** React code content */
  content: string;
  /** File path */
  path: string;
  /** Chat room ID */
  room_id: string;
  /** Question timestamp (ms) */
  question_created_at: number;
  /** Answer timestamp (ms) */
  answer_created_at: number;
  /** Response status */
  status: Status;
  /** SHA-256 hash of content (64 hex chars). NULL if no code. STORED column (migration 004). 표시는 7자 약식(shortHash), 비교는 풀 해시 */
  code_hash?: string | null;
}

/**
 * Description generation reason
 */
export type DescriptionReason = 'initial' | 'regenerated_with_edits' | 'regenerated';

/**
 * AI-generated UI descriptions with version management
 * Collection: descriptions
 */
export interface Description {
  /** Description ID (UUID) */
  id: string;
  /** Chat room ID (FK) */
  room_id: string;
  /** AI-generated description text */
  content: string;
  /** Integer version (1, 2, 3...). Incremented only on AI extraction */
  version: number;
  /** Generation reason */
  reason: DescriptionReason;
  /** User-edited content (null if not edited) */
  edited_content: string | null;
  /** Created timestamp (ms) */
  created_at: number;
  /** SHA-256 hash of display text (edited_content ?? content), 64 hex chars. STORED column (migration 004) */
  description_hash?: string | null;
  /** description_hash 의 git 약식(앞 7자). 서버 응답(REST)에만 존재하는 표시 전용 값 */
  description_hash_short?: string | null;
}

/**
 * Summary for version list (without full content)
 */
export interface DescriptionVersionSummary {
  id: string;
  version: number;
  reason: DescriptionReason;
  created_at: number;
}

/**
 * Edit history for re-extraction context
 */
export interface EditHistory {
  original_content: string;
  edited_content: string;
  base_version: number;
}
