package designtoken

// GeneratedFile represents a file generated by the CVA generator.
type GeneratedFile struct {
	Path        string `json:"path"`
	Type        string `json:"type"`
	Description string `json:"description"`
}
