#!/usr/bin/env python3
"""
Generate Python files from JSON source
Usage: python generate-python.py
"""

import json
from pathlib import Path

FIREBASE_DIR = Path(__file__).parent.parent / "firebase"
OUTPUT_DIR = Path(__file__).parent.parent / "python" / "firebase"


def ensure_output_dir():
    """Ensure output directory exists"""
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)


def to_pascal_case(snake_str: str) -> str:
    """snake_case to PascalCase 변환"""
    return "".join(word.capitalize() for word in snake_str.split("_"))


def json_type_to_python(field: dict) -> str:
    """JSON type to Python type 변환"""
    if "enum" in field:
        return "MessageStatus"  # Will be replaced with actual enum name
    type_map = {
        "string": "str",
        "number": "int",
        "boolean": "bool",
        "array": "list",
        "object": "dict",
    }
    return type_map.get(field.get("type", ""), "Any")


def generate_collections():
    """Generate collections.py"""
    with open(FIREBASE_DIR / "collections.json") as f:
        data = json.load(f)

    # Generate Collections class
    entries = []
    for key, value in data["collections"].items():
        const_name = key.upper()
        collection_name = value["name"]
        description = value["description"]
        entries.append(f'    {const_name} = "{collection_name}"  # {description}')

    output = '''"""
Firebase Firestore Collection Names

⚠️ AUTO-GENERATED - DO NOT EDIT MANUALLY
Source: packages/shared-types/firebase/collections.json
Generated by: scripts/generate-python.py
"""


class Collections:
    """Firestore collection names"""

{entries}
'''.format(entries="\n".join(entries))

    with open(OUTPUT_DIR / "collections.py", "w") as f:
        f.write(output)

    print("✅ Generated: python/firebase/collections.py")


def generate_types():
    """Generate types.py from collection fields"""
    with open(FIREBASE_DIR / "collections.json") as f:
        data = json.load(f)

    type_defs = []
    class_names = []

    for collection_key, collection in data["collections"].items():
        if "fields" not in collection:
            continue

        # chat_rooms -> ChatRoom (remove trailing 's')
        class_name = to_pascal_case(collection_key.rstrip("s"))
        class_names.append(class_name)

        # Check for enum fields
        enum_types = []
        for field_name, field in collection["fields"].items():
            if "enum" in field:
                enum_name = to_pascal_case(field_name)
                enum_values = ", ".join(f'"{v}"' for v in field["enum"])
                enum_types.append(f'{enum_name} = Literal[{enum_values}]')
                class_names.append(enum_name)

        # Generate TypedDict fields
        fields = []
        for field_name, field in collection["fields"].items():
            if "enum" in field:
                py_type = to_pascal_case(field_name)
            else:
                py_type = json_type_to_python(field)
            comment = f"  # {field['description']}" if "description" in field else ""
            fields.append(f"    {field_name}: {py_type}{comment}")

        class_code = f'''class {class_name}(TypedDict):
    """
    {collection["description"]}
    Collection: {collection["name"]}
    """

{chr(10).join(fields)}'''

        if enum_types:
            type_defs.extend(enum_types)
            type_defs.append("")  # blank line

        type_defs.append(class_code)

    output = '''"""
Firebase Firestore Document Types

⚠️ AUTO-GENERATED - DO NOT EDIT MANUALLY
Source: packages/shared-types/firebase/collections.json
Generated by: scripts/generate-python.py
"""

from typing import Literal, TypedDict


{type_defs}
'''.format(type_defs="\n\n".join(type_defs))

    with open(OUTPUT_DIR / "types.py", "w") as f:
        f.write(output)

    print("✅ Generated: python/firebase/types.py")

    return class_names


def generate_storage():
    """Generate storage.py"""
    with open(FIREBASE_DIR / "storage.json") as f:
        data = json.load(f)

    entries = []
    for key, value in data["paths"].items():
        const_name = key.upper()
        path_name = value["path"]
        description = value["description"]
        entries.append(f'    {const_name} = "{path_name}"  # {description}')

    output = '''"""
Firebase Storage Paths

⚠️ AUTO-GENERATED - DO NOT EDIT MANUALLY
Source: packages/shared-types/firebase/storage.json
Generated by: scripts/generate-python.py
"""


class StoragePaths:
    """Firebase Storage path constants"""

{entries}
'''.format(entries="\n".join(entries))

    with open(OUTPUT_DIR / "storage.py", "w") as f:
        f.write(output)

    print("✅ Generated: python/firebase/storage.py")


def generate_init(type_exports: list[str]):
    """Generate __init__.py"""
    type_imports = ", ".join(type_exports)

    output = '''"""
Firebase Shared Configuration

⚠️ AUTO-GENERATED - DO NOT EDIT MANUALLY
Generated by: scripts/generate-python.py
"""

from .collections import Collections
from .storage import StoragePaths
from .types import {type_imports}

__all__ = ["Collections", "StoragePaths", {all_exports}]
'''.format(
        type_imports=type_imports,
        all_exports=", ".join(f'"{name}"' for name in ["Collections", "StoragePaths"] + type_exports)
    )

    with open(OUTPUT_DIR / "__init__.py", "w") as f:
        f.write(output)

    print("✅ Generated: python/firebase/__init__.py")


def main():
    """Run generation"""
    try:
        print("🔄 Generating Python files...\n")
        ensure_output_dir()
        generate_collections()
        type_exports = generate_types()
        generate_storage()
        generate_init(type_exports)
        print("\n✨ Python generation complete!")
    except Exception as e:
        print(f"❌ Error generating Python files: {e}")
        raise


if __name__ == "__main__":
    main()
