#!/usr/bin/env python3
"""
Generate Python files from JSON source
Usage: python generate-python.py
"""

import json
import os
from pathlib import Path

FIREBASE_DIR = Path(__file__).parent.parent / "firebase"
OUTPUT_DIR = Path(__file__).parent.parent / "python" / "firebase"


def ensure_output_dir():
    """Ensure output directory exists"""
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)


def generate_collections():
    """Generate collections.py"""
    with open(FIREBASE_DIR / "collections.json") as f:
        data = json.load(f)

    entries = []
    for key, value in data["collections"].items():
        const_name = key.upper()
        collection_name = value["name"]
        description = value["description"]
        entries.append(f'    {const_name} = "{collection_name}"  # {description}')

    output = '''"""
Firebase Firestore Collection Names

⚠️ AUTO-GENERATED - DO NOT EDIT MANUALLY
Source: packages/shared-types/firebase/collections.json
Generated by: scripts/generate-python.py
"""


class Collections:
    """Firestore collection names"""

{entries}
'''.format(entries='\n'.join(entries))

    with open(OUTPUT_DIR / "collections.py", "w") as f:
        f.write(output)

    print("✅ Generated: python/firebase/collections.py")


def generate_storage():
    """Generate storage.py"""
    with open(FIREBASE_DIR / "storage.json") as f:
        data = json.load(f)

    entries = []
    for key, value in data["paths"].items():
        const_name = key.upper()
        path_name = value["path"]
        description = value["description"]
        entries.append(f'    {const_name} = "{path_name}"  # {description}')

    output = '''"""
Firebase Storage Paths

⚠️ AUTO-GENERATED - DO NOT EDIT MANUALLY
Source: packages/shared-types/firebase/storage.json
Generated by: scripts/generate-python.py
"""


class StoragePaths:
    """Firebase Storage path constants"""

{entries}
'''.format(entries='\n'.join(entries))

    with open(OUTPUT_DIR / "storage.py", "w") as f:
        f.write(output)

    print("✅ Generated: python/firebase/storage.py")


def generate_init():
    """Generate __init__.py"""
    output = '''"""
Firebase Shared Configuration

⚠️ AUTO-GENERATED - DO NOT EDIT MANUALLY
Generated by: scripts/generate-python.py
"""

from .collections import Collections
from .storage import StoragePaths

__all__ = ["Collections", "StoragePaths"]
'''

    with open(OUTPUT_DIR / "__init__.py", "w") as f:
        f.write(output)

    print("✅ Generated: python/firebase/__init__.py")


def main():
    """Run generation"""
    try:
        print("🔄 Generating Python files...\n")
        ensure_output_dir()
        generate_collections()
        generate_storage()
        generate_init()
        print("\n✨ Python generation complete!")
    except Exception as e:
        print(f"❌ Error generating Python files: {e}")
        exit(1)


if __name__ == "__main__":
    main()
