// component-definitions-hash: 841b47f62835243610a11f574cd1fe5c5e6600316eec8c3b4738c810c5b4be05
export const palette = {
  'brand-blue-50': '#e1eaff',
  'brand-blue-100': '#c3d6ff',
  'brand-blue-200': '#98b3ee',
  'brand-blue-300': '#698fe0',
  'brand-blue-600': '#0033a0',
  'brand-blue-500': '#154cc1',
  'brand-blue-400': '#3e6ccf',
  'brand-blue-700': '#002480',
  'brand-blue-800': '#001d63',
  'brand-blue-900': '#00154a',
  'neutral-gray-0': '#ffffff',
  'neutral-gray-50': '#f9fafb',
  'neutral-gray-100': '#f4f6f8',
  'neutral-gray-200': '#e9ecef',
  'neutral-gray-300': '#dee2e6',
  'neutral-gray-400': '#ced4da',
  'neutral-gray-500': '#9da4ab',
  'neutral-gray-600': '#6c757d',
  'neutral-gray-700': '#495057',
  'neutral-gray-800': '#343a40',
  'neutral-gray-900': '#212529',
  'semantic-warning-500': '#ed6c02',
  'semantic-success-500': '#2e7d32',
  'semantic-error-500': '#d32f2f',
  'semantic-info-500': '#0288d1',
  'tint-brand-primary-500-08': '#ecf0fa',
  'tint-brand-primary-500-12': '#e2e9f7',
  'tint-brand-primary-500-16': '#d9e2f5',
  'tint-brand-primary-500-20': '#d0dbf2',
  'neutral-gray-150': '#eceff3',
  'tint-success-500-08': '#eef5ef',
  'tint-success-500-12': '#e6efe6',
  'tint-success-500-16': '#deeade',
  'tint-info-500-08': '#ebf5fb',
  'tint-warning-500-08': '#fef3eb',
  'tint-error-500-08': '#fbeeee',
  'tint-info-500-12': '#e1f1f9',
  'tint-info-500-16': '#d7ecf8',
  'tint-warning-500-12': '#fdede1',
  'tint-warning-500-16': '#fce7d7',
  'tint-error-500-12': '#fae6e6',
  'tint-error-500-16': '#f8dede',
  'semantic-success-700': '#1e4620',
  'semantic-info-700': '#014361',
  'semantic-warning-700': '#663c00',
  'semantic-error-700': '#5f2120',
  'neutral-gray-1000': '#000000',
  'neutral-gray-450': '#bfc5cc',
  'overlay-gray-1000-04': 'rgba(0, 0, 0, 0.04)',
  'overlay-gray-1000-06': 'rgba(0, 0, 0, 0.06)',
  'overlay-gray-1000-08': 'rgba(0, 0, 0, 0.08)',
  'overlay-gray-1000-10': 'rgba(0, 0, 0, 0.10)',
  'overlay-gray-1000-12': 'rgba(0, 0, 0, 0.12)',
  'overlay-gray-1000-56': 'rgba(0, 0, 0, 0.56)',
  'hue-red-500': '#ef4444',
  'hue-red-800': '#991b1b',
  'hue-orange-500': '#f97316',
  'hue-orange-800': '#9a3412',
  'hue-yellow-500': '#eab308',
  'hue-yellow-800': '#854d0e',
  'hue-lime-500': '#84cc16',
  'hue-lime-800': '#3f6212',
  'hue-green-500': '#22c55e',
  'hue-green-800': '#166534',
  'hue-cyan-500': '#06b6d4',
  'hue-cyan-800': '#155e75',
  'hue-violet-500': '#8b5cf6',
  'hue-violet-800': '#5b21b6',
  'hue-pink-500': '#ec4899',
  'hue-pink-800': '#9d174d',
  'tint-red-500-12': '#fde9e9',
  'tint-orange-500-12': '#feeee3',
  'tint-yellow-500-12': '#fcf6e1',
  'tint-lime-500-12': '#f0f9e3',
  'tint-green-500-12': '#e4f8ec',
  'tint-cyan-500-12': '#e1f6fa',
  'tint-violet-500-12': '#f1ebfe',
  'tint-pink-500-12': '#fde9f3',
  'hue-red-300': '#f58e8e',
  'hue-orange-300': '#fbab73',
  'hue-yellow-300': '#f2d16a',
  'hue-lime-300': '#b5e073',
  'hue-green-300': '#7adc9e',
  'hue-violet-300': '#b99df9',
  'hue-pink-300': '#f391c1',
  'hue-cyan-300': '#69d3e5',
  'overlay-gray-1000-00': 'rgba(0, 0, 0, 0.00)',
  'overlay-white-0-08': 'rgba(255, 255, 255, 0.12)',
  'overlay-white-0-16': 'rgba(255, 255, 255, 0.16)',
} as const;

export const role = {
  'overlay-scrim': palette['overlay-gray-1000-56'],
  'brand-primary': palette['brand-blue-600'],
  'brand-primary-hover': palette['brand-blue-500'],
  'brand-primary-pressed': palette['brand-blue-700'],
  'text-primary': palette['neutral-gray-900'],
  'text-secondary': palette['neutral-gray-700'],
  'text-disabled': palette['neutral-gray-500'],
  'bg-canvas': palette['neutral-gray-100'],
  'bg-surface': palette['neutral-gray-0'],
  'bg-subtle': palette['neutral-gray-150'],
  'border-default': palette['neutral-gray-300'],
  'border-subtle': palette['neutral-gray-200'],
  'semantic-success': palette['semantic-success-500'],
  'semantic-warning': palette['semantic-warning-500'],
  'semantic-error': palette['semantic-error-500'],
  'semantic-info': palette['semantic-info-500'],
  'chip-bg-selected': palette['tint-brand-primary-500-08'],
  'control-stroke-default': palette['neutral-gray-400'],
  'control-stroke-disabled': palette['neutral-gray-300'],
  'control-bg-on': palette['brand-blue-600'],
  'control-bg-disabled': palette['neutral-gray-400'],
  'control-icon-on': palette['neutral-gray-0'],
  'control-icon-disabled': palette['neutral-gray-500'],
  'control-icon-selected': palette['brand-blue-600'],
  'control-bg-off': palette['neutral-gray-400'],
  'control-knob-off': palette['neutral-gray-0'],
  'control-knob-on': palette['neutral-gray-0'],
  'control-knob-disabled': palette['neutral-gray-150'],
  'icon-interactive-default': palette['neutral-gray-700'],
  'icon-interactive-on-selection': palette['brand-blue-600'],
  'icon-decorative-default': palette['neutral-gray-700'],
  'icon-decorative-tertiary': palette['neutral-gray-600'],
  'icon-semantic-success': palette['semantic-success-500'],
  'icon-semantic-error': palette['semantic-error-500'],
  'icon-interactive-disabled': palette['neutral-gray-500'],
  'icon-semantic-info': palette['semantic-info-500'],
  'icon-interactive-inverse': palette['neutral-gray-0'],
  'focus': palette['brand-blue-600'],
  'text-inverse': palette['neutral-gray-0'],
  'chip-bg-off': palette['neutral-gray-150'],
  'chip-bg-disabled': palette['neutral-gray-150'],
  'chip-bg-selected-hover': palette['tint-brand-primary-500-12'],
  'chip-bg-selected-pressed': palette['tint-brand-primary-500-16'],
  'border-accent': palette['brand-blue-600'],
  'text-accent': palette['brand-blue-600'],
  'text-semantic-on-success': palette['semantic-success-700'],
  'text-semantic-on-info': palette['semantic-info-700'],
  'text-semantic-on-warning': palette['semantic-warning-700'],
  'text-semantic-on-error': palette['semantic-error-700'],
  'alert-success-bg': palette['tint-success-500-12'],
  'alert-success-text': palette['semantic-success-700'],
  'alert-info-bg': palette['tint-info-500-12'],
  'alert-info-text': palette['semantic-info-700'],
  'alert-warning-bg': palette['tint-warning-500-12'],
  'alert-warning-text': palette['semantic-warning-700'],
  'alert-error-bg': palette['tint-error-500-12'],
  'alert-error-text': palette['semantic-error-700'],
  'field-bg-surface': palette['neutral-gray-0'],
  'field-bg-disabled': palette['neutral-gray-150'],
  'field-bg-readonly': palette['neutral-gray-150'],
  'field-border-default': palette['neutral-gray-300'],
  'field-border-focus': palette['brand-blue-600'],
  'field-border-disabled': palette['neutral-gray-300'],
  'field-border-error': palette['semantic-error-500'],
  'field-border-warning': palette['semantic-warning-500'],
  'field-border-success': palette['semantic-success-500'],
  'field-text-placeholder': palette['neutral-gray-600'],
  'field-text-help': palette['neutral-gray-700'],
  'text-tertiary': palette['neutral-gray-600'],
  'field-caret': palette['brand-blue-600'],
  'field-bg-filled': palette['overlay-gray-1000-04'],
  'chart-series-1': palette['brand-blue-600'],
  'chart-series-2': palette['brand-blue-400'],
  'chart-series-3': palette['brand-blue-200'],
  'chart-series-5': palette['neutral-gray-500'],
  'chart-series-6': palette['neutral-gray-600'],
  'chart-label': palette['neutral-gray-800'],
  'chart-label-inverse': palette['neutral-gray-0'],
  'chart-axis-line': palette['neutral-gray-300'],
  'chart-series-4': palette['brand-blue-300'],
  'chart-series-line': palette['brand-blue-900'],
  'icon-semantic-warning': palette['semantic-warning-500'],
  'badge-primary-solid-bg': palette['brand-blue-600'],
  'badge-status-info-subtle-text': palette['semantic-info-700'],
  'badge-status-info-subtle-bg': palette['tint-info-500-12'],
  'badge-status-success-subtle-bg': palette['tint-success-500-12'],
  'badge-status-success-subtle-text': palette['semantic-success-700'],
  'badge-status-warning-subtle-bg': palette['tint-warning-500-12'],
  'badge-status-warning-subtle-text': palette['semantic-warning-700'],
  'badge-status-error-subtle-bg': palette['tint-error-500-12'],
  'badge-status-error-subtle-text': palette['semantic-error-700'],
  'brand-secondary': palette['brand-blue-200'],
  'brand-secondary-hover': palette['brand-blue-300'],
  'brand-secondary-pressed': palette['brand-blue-400'],
  'bg-selection': palette['tint-brand-primary-500-08'],
  'border-strong': palette['neutral-gray-400'],
  'state-overlay-on-neutral-pressed': palette['overlay-gray-1000-10'],
  'state-overlay-on-neutral-hover': palette['overlay-gray-1000-06'],
  'state-overlay-on-colored-hover': palette['overlay-gray-1000-08'],
  'state-overlay-on-colored-pressed': palette['overlay-gray-1000-12'],
  'bg-container-low': palette['overlay-gray-1000-04'],
  'bg-container-medium': palette['overlay-gray-1000-08'],
  'bg-container-high': palette['overlay-gray-1000-12'],
  'text-on-selection': palette['brand-blue-600'],
  'icon-decorative-accent': palette['brand-blue-600'],
  'border-selection': palette['brand-blue-600'],
  'brand-selection-hover': palette['tint-brand-primary-500-12'],
  'brand-selection-pressed': palette['tint-brand-primary-500-16'],
  'border-disabled': palette['neutral-gray-300'],
  'bg-disabled-on-light': palette['neutral-gray-150'],
  'bg-disabled-on-filled': palette['neutral-gray-400'],
  'bg-accent': palette['brand-blue-600'],
  'bg-text-selection': palette['tint-brand-primary-500-20'],
  'bg-semantic-info-subtle': palette['tint-info-500-12'],
  'bg-semantic-success-subtle': palette['tint-success-500-12'],
  'bg-semantic-warning-subtle': palette['tint-warning-500-12'],
  'bg-semantic-error-subtle': palette['tint-error-500-12'],
  'bg-accent-subtle': palette['tint-brand-primary-500-16'],
  'bg-semantic-info': palette['semantic-info-500'],
  'bg-semantic-success': palette['semantic-success-500'],
  'bg-semantic-warning': palette['semantic-warning-500'],
  'bg-semantic-error': palette['semantic-error-500'],
  'badge-solid-text': palette['neutral-gray-0'],
  'badge-primary-subtle-bg': palette['tint-brand-primary-500-16'],
  'badge-primary-subtle-text': palette['brand-blue-600'],
  'tag-default-bg': palette['neutral-gray-150'],
  'tag-default-text': palette['neutral-gray-900'],
  'tag-more-border': palette['neutral-gray-300'],
  'tag-more-bg': palette['neutral-gray-0'],
  'text-semantic-error': palette['semantic-error-500'],
  'border-contrast': palette['neutral-gray-0'],
  'bg-accent-secondary': palette['brand-blue-200'],
  'border-semantic-info': palette['semantic-info-500'],
  'border-semantic-success': palette['semantic-success-500'],
  'border-semantic-warning': palette['semantic-warning-500'],
  'border-semantic-error': palette['semantic-error-500'],
  'text-semantic-info': palette['semantic-info-500'],
  'segment-group-bg': palette['neutral-gray-0'],
  'segment-item-bg-selected': palette['tint-brand-primary-500-08'],
  'icon-interactive-on-secondary': palette['neutral-gray-900'],
  'overlay-transparent': palette['overlay-gray-1000-00'],
  'state-overlay-on-inverse-hover': palette['overlay-white-0-08'],
  'state-overlay-on-inverse-pressed': palette['overlay-white-0-16'],
} as const;

export const space = {
  'scale-0': '0px',
  'scale-2': '2px',
  'scale-4': '4px',
  'scale-6': '6px',
  'scale-8': '8px',
  'scale-12': '12px',
  'scale-16': '16px',
  'scale-20': '20px',
  'scale-24': '24px',
  'scale-32': '32px',
  'scale-40': '40px',
  'scale-48': '48px',
  'scale-64': '64px',
  'scale-10': '10px',
  'scale-14': '14px',
  'scale-56': '56px',
  'scale-72': '72px',
} as const;

export const typography = {
  'heading-xl-bold': {
    fontFamily: 'Pretendard',
    fontWeight: '700',
    fontSize: '28px',
    lineHeight: '36px',
  },
  'heading-lg-bold': {
    fontFamily: 'Pretendard',
    fontWeight: '700',
    fontSize: '24px',
    lineHeight: '32px',
  },
  'heading-md-semibold': {
    fontFamily: 'Pretendard',
    fontWeight: '600',
    fontSize: '20px',
    lineHeight: '28px',
  },
  'body-lg-medium': {
    fontFamily: 'Pretendard',
    fontWeight: '500',
    fontSize: '18px',
    lineHeight: '28px',
  },
  'body-lg-regular': {
    fontFamily: 'Pretendard',
    fontWeight: '400',
    fontSize: '18px',
    lineHeight: '28px',
  },
  'body-md-medium': {
    fontFamily: 'Pretendard',
    fontWeight: '500',
    fontSize: '16px',
    lineHeight: '24px',
  },
  'body-md-regular': {
    fontFamily: 'Pretendard',
    fontWeight: '400',
    fontSize: '16px',
    lineHeight: '24px',
  },
  'body-sm-medium': {
    fontFamily: 'Pretendard',
    fontWeight: '500',
    fontSize: '14px',
    lineHeight: '20px',
  },
  'body-sm-regular': {
    fontFamily: 'Pretendard',
    fontWeight: '400',
    fontSize: '14px',
    lineHeight: '20px',
  },
  'caption-sm-medium': {
    fontFamily: 'Pretendard',
    fontWeight: '500',
    fontSize: '14px',
    lineHeight: '20px',
  },
  'caption-sm-regular': {
    fontFamily: 'Pretendard',
    fontWeight: '400',
    fontSize: '14px',
    lineHeight: '20px',
  },
  'caption-xs-medium': {
    fontFamily: 'Pretendard',
    fontWeight: '500',
    fontSize: '14px',
    lineHeight: '16px',
  },
  'caption-xs-regular': {
    fontFamily: 'Pretendard',
    fontWeight: '400',
    fontSize: '14px',
    lineHeight: '16px',
  },
  'navigation-menu-medium': {
    fontFamily: 'Pretendard',
    fontWeight: '500',
    fontSize: '14px',
    lineHeight: '20px',
  },
  'navigation-menu-regular': {
    fontFamily: 'Pretendard',
    fontWeight: '400',
    fontSize: '14px',
    lineHeight: '20px',
  },
  'form-label-md-medium': {
    fontFamily: 'Pretendard',
    fontWeight: '500',
    fontSize: '16px',
    lineHeight: '24px',
  },
  'form-label-sm-medium': {
    fontFamily: 'Pretendard',
    fontWeight: '500',
    fontSize: '14px',
    lineHeight: '20px',
  },
  'form-helper-text-md-regular': {
    fontFamily: 'Pretendard',
    fontWeight: '400',
    fontSize: '14px',
    lineHeight: '20px',
  },
  'form-helper-text-sm-regular': {
    fontFamily: 'Pretendard',
    fontWeight: '400',
    fontSize: '12px',
    lineHeight: '20px',
  },
  'table-header-medium': {
    fontFamily: 'Pretendard',
    fontWeight: '500',
    fontSize: '16px',
    lineHeight: '24px',
  },
  'table-cell-text-regular': {
    fontFamily: 'Pretendard',
    fontWeight: '400',
    fontSize: '16px',
    lineHeight: '24px',
  },
  'table-cell-number-regular-num': {
    fontFamily: 'Pretendard',
    fontWeight: '400',
    fontSize: '16px',
    lineHeight: '24px',
  },
  'table-caption-regular': {
    fontFamily: 'Pretendard',
    fontWeight: '400',
    fontSize: '14px',
    lineHeight: '20px',
  },
  'chart-axis-label-regular': {
    fontFamily: 'Pretendard',
    fontWeight: '400',
    fontSize: '14px',
    lineHeight: '20px',
  },
  'chart-graph-label-medium-num': {
    fontFamily: 'Pretendard',
    fontWeight: '500',
    fontSize: '14px',
    lineHeight: '20px',
  },
  'chart-legend-medium': {
    fontFamily: 'Pretendard',
    fontWeight: '500',
    fontSize: '14px',
    lineHeight: '20px',
  },
  'button-lg-medium': {
    fontFamily: 'Pretendard',
    fontWeight: '500',
    fontSize: '18px',
    lineHeight: '24px',
  },
  'button-md-medium': {
    fontFamily: 'Pretendard',
    fontWeight: '500',
    fontSize: '16px',
    lineHeight: '20px',
  },
  'button-sm-medium': {
    fontFamily: 'Pretendard',
    fontWeight: '500',
    fontSize: '14px',
    lineHeight: '20px',
  },
  'chip-label-md-medium': {
    fontFamily: 'Pretendard',
    fontWeight: '500',
    fontSize: '14px',
    lineHeight: '20px',
  },
  'chip-label-sm-medium': {
    fontFamily: 'Pretendard',
    fontWeight: '500',
    fontSize: '12px',
    lineHeight: '16px',
  },
  'display-value-xxxl-bold-num': {
    fontFamily: 'Pretendard',
    fontWeight: '700',
    fontSize: '32px',
    lineHeight: '40px',
  },
  'display-value-xxl-semibold-num': {
    fontFamily: 'Pretendard',
    fontWeight: '600',
    fontSize: '28px',
    lineHeight: '36px',
  },
  'display-value-xl-semibold-num': {
    fontFamily: 'Pretendard',
    fontWeight: '600',
    fontSize: '24px',
    lineHeight: '32px',
  },
  'display-caption-md-medium': {
    fontFamily: 'Pretendard',
    fontWeight: '500',
    fontSize: '16px',
    lineHeight: '20px',
  },
  'display-caption-lg-medium': {
    fontFamily: 'Pretendard',
    fontWeight: '500',
    fontSize: '18px',
    lineHeight: '24px',
  },
  'display-unit-lg-medium': {
    fontFamily: 'Pretendard',
    fontWeight: '500',
    fontSize: '18px',
    lineHeight: '24px',
  },
  'display-indicator-md-medium': {
    fontFamily: 'Pretendard',
    fontWeight: '500',
    fontSize: '16px',
    lineHeight: '20px',
  },
} as const;

